### ISSUE TITLE
Draft Terms and Conditions this service will need to provide for first version of alpha

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#198]
-Does it need one for alpha?
-What information is collected or not?

**Comment by rjmajma** [comment]
I'll look into seeing what needs doing here. 

At a minimum, we want some language that states the information is accurate to the best of our knowledge.

**Comment by khandelwal** [comment]
If we can get this language relatively soon, it'll be easier to include it into the app during the current sprint.

**Comment by rjmajma** [comment]
I believe the language is already in the content changes that Kate recommended. You should have it, I think. If not, I can remedy quickly.

**Comment by khandelwal** [comment]
It's there. Real lawyers would think it is subtle. I am ok with that.

**Comment by khandelwal** [comment]
Did I say real lawyers? I'm sorry. I might have meant like other lawyers. Definitely wouldn't make fun of product-manager-lawyer people.
