### ISSUE TITLE
Doesn't search names of agencies

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#242]
If you search for 'Federal Bureau of Investigation' you'll notice that the names of agencies aren't searched. Descriptions are, which is why 'Department of Commerce' works because the name of the agency is in it's description. I don't think this is true of the Federal Bureau of Investigation. 

At the very least, if I have typed in the full name of the agency, I should probably see that result first.

**Comment by rjmajma** [comment]
Resolved between #348 and #419.
