### ISSUE TITLE
Add "official" banner and "alpha" banner

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#260]
One of these, e.g. from [18f-site](https://18f.gsa.gov):

![one of these](https://cloud.githubusercontent.com/assets/4592/5133019/8afe3e58-70cf-11e4-9215-460412a92b0a.png)

Should not go up without a corresponding "This is an alpha!" banner like [MyRA](https://myra.treasury.gov) has:

![from myra](https://cloud.githubusercontent.com/assets/4592/5133095/2bc1b072-70d0-11e4-83f6-c5a761739ff8.png)

**Comment by rjmajma** [comment]
Resolved with #422.
