### ISSUE TITLE
Reconsider Using the Average

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#317]
DOJ argues that average processing time more accurately describes time requesters will have to wait. Also, they noted that many agencies are missing the median. 

I ran a couple queries on the 2013 data to look for missing data:
```ipython
Average Simple Missing: 37
Median Simple Missing: 39

Average Complex Missing: 105
Median Complex Missing: 107
```

**Comment by rjmajma** [comment]
@ramirezg has decided that we are sticking with the median.

We may change the context for this depending on user feedback.
