### ISSUE TITLE
New copy for "What is FOIA?" on the home page

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#330]
Currently, the copy introduces the user to the concept of FOIA. It may be a better use of the space to introduce the user to the site instead. 

One thing to consider: can we introduce the user to the concept of the FOIA Libraries (and how to search them) here?

**Comment by khandelwal** [comment]
What's the final copy here?

**Comment by rjmajma** [comment]
Let's go with Jesse's copy, delete the section under bit, and change the search bar copy as well. 

Final: 

For the section in blue font:
FOIA Hub is the first front door to the United States Freedom of Information Act request process that includes current contact information for every federal agency.

Delete for the section under.

Change "Which agency do you want to contact?" to "Search for agency by name, abbreviation or keyword"

**Comment by jtag** [comment]
@rjmajma Can you provide final copy for all these type of content stories in a more final version so @vz3 and @ericadeahl  know what final copy to include? One new clean issues or a google doc?

**Comment by rjmajma** [comment]
Here it is! https://docs.google.com/a/gsa.gov/document/d/1k5LTS7eRPr_lXwvQM6SnBSDCr8mq5dpNz8U1sYdPWmk/edit?usp=sharing

**Comment by khandelwal** [comment]
Can this issue be closed?

**Comment by rjmajma** [comment]
Yup! Good call, thanks @khandelwal.
