### ISSUE TITLE
New copy for "How does the process work?" on the Home Page

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#331]
We currently have empty gray squares with copy underneath that describes the FOIA process. This should be kept to 4 squares and be easy to understand.

**Comment by khandelwal** [comment]
What's the final copy here?

**Comment by rjmajma** [comment]
Final copy is what Jesse posted:

1. Submit a FOIA request directly to the agency you believe holds the information you seek.
2. The FOIA officials at that agency will (usually) email receipt of your request and begin looking for the requested records or point you to a public space where the records may already be accessed.
3. As the records are collected, they will be assessed to determine what can be provided to the requestor.
4. FOIA officials at the agency send the requester their "determination. The records may be in full, partial or redacted or denied as a request.
