### ISSUE TITLE
Update Emails that Bounced

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#347]
Emails that bounced were deleted on issue #216 and some replacements were made for agencies that provided and updated email. Now we need a list of updated emails for those that bounced from #218 
This task has 2 parts:
- [x] Collect a list of updated emails
- [x] validate they are correct (possibly by sending the same email from #216)

**Comment by rjmajma** [comment]
Hey folks, just checking in on the status of this ticket. What's the word?

**Comment by konklone** [comment]
```
Hi,

We (a GSA team working on FOIA) are sending this email to around 20 email addresses that have been provided to us as updated or fixed points of contact for FOIA offices within the federal government.

**You do not need to reply to this message.** We are sending this message only to watch for automated bounces, in order to validate that the email address is functional and that there were no typos or miscommunication.

Thanks very much,
18F's Team FOIA
```

**Comment by ramirezg** [comment]
Done
