### ISSUE TITLE
Determine Look and Feel by comping up Home Page

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#352]
Happy to chat more and follow up from our first discussion.

**Comment by khandelwal** [comment]
Re: a logo sketching session - it might actually be fun and useful to include the rest of the team on the logo sketching session. Joint sketching sessions for features have worked really well for teams I've been on in the past.

**Comment by khandelwal** [comment]
A few comments: 

#### Responsiveness

What do narrower versions of these pages (for mobile, for example) look like? 

#### Agency Landing Page
On the agency landing page, putting a white box around the FOIA Library, Public Liaison etc. section calls attention to that information. We should carefully consider what goes in that box. 

Does the public liaison belong there? Do we want people calling the PL? Also, why is there only a phone number and not an email address for this person?

The processing time is only useful if you are considering submitting a request. Should it move closer to the submit a request section?

Should the order of request methods be: online, email, fax, address?

**Comment by corizarek** [comment]
@ericadeahl This looks fantastic! Love it. Really clean and modern.

@khandelwal -- the Public Liaison definitely belongs. That person is charged with being the resource to the public on anything FOIA-related (should be the first person a requester contacts for assistance). We should talk with DOJ about also collecting those email addresses (some of them may be listed on agency webpages). 

No preference on location of processing time (could see it either way).

Agree re order of request methods.

Go team go!

**Comment by jtag** [comment]
Reviewed with Victor and he and Erica have enough to move forward.
