### ISSUE TITLE
Missing offices? 

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#380]
The DOJ collects data on offices such as OIG/HUD that aren't on foia.gov/report-makerequest.html or our database. 

Foia.gov/data actually has data on at least 50+ offices that we don't have in our database, should we add them?

**Comment by ramirezg** [comment]
DOJ says they just contacted HUD to ask about their contact info. As for other departments, some like ED prefer a centralized location for FOIA requests but report data for multiple offices. 

I'll leave this ticket open till I hear specifically about HUD/OIG.

**Comment by rjmajma** [comment]
Hey @ramirezg and @khandelwal, is it worth putting this in the backlog till we have a better idea of when we'll hear back about HUD/OIG?

**Comment by ramirezg** [comment]
I agencies have just reorganized. We can close this issue.
