### ISSUE TITLE
Only sub-agencies have parent agencies

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#385]
Currently only sub-agencies (agencies with top_level = true) have parent agencies. Maybe we should implement the same structure to regular offices. 

[sub_agency.parent = a](https://github.com/18F/foia-hub/blob/master/foia_hub/scripts/load_agency_contacts.py#L188-L192)

**Comment by khandelwal** [comment]
I don't understand this issue. Can you elaborate? 

Offices know which agency they are part of: 
https://github.com/18F/foia-hub/blob/master/foia_hub/models.py#L143

**Comment by ramirezg** [comment]
Whoops, I should have looked more closely. It gets added here:
https://github.com/18F/foia-hub/blob/master/foia_hub/scripts/load_agency_contacts.py#L218
