### ISSUE TITLE
Design alpha messaging/banner

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#392]

**Comment by ericadeahl** [comment]
@vz3 @jtag 

I was thinking something like this for the alpha banner, though it feels very stripe-y.
![foia_alphabanner_1](https://cloud.githubusercontent.com/assets/5911280/5685079/bd141bd6-97eb-11e4-9490-811bddec8a00.png)

Perhaps to lessen that it could sit at the bottom of the browser window. Thoughts?
![foia_alphabanner_2](https://cloud.githubusercontent.com/assets/5911280/5685089/d1b38536-97eb-11e4-8df7-72ca4793c615.png)

Also, not sure where 'Help us improve' would lead. Are you just having people email comments? Is it helpful to surface that in the banner?

**Comment by jtag** [comment]
Great question. Either is the foia email or would go to our issues. I think
email is more user friendly for our audiences. 18F-foia@gsa.gov. Probably
best to just type it b/c if you click it as a link you get stuck with it
bringing up mac mail or other email programs you might not actually be
using.

re stripey: I'm okay with that aspect. Color is a bit intense. Could/shoudl
it relate to color of alpha here? https://18f.gsa.gov/dashboard/  (hmm..
which will probably be designed...).

Alpha should link to the dashboard so it provides a description of that
means.



On Fri, Jan 9, 2015 at 10:43 AM, Erica Deahl <notifications@github.com>
wrote:

> @vz3 <https://github.com/vz3> @jtag <https://github.com/jtag>
>
> I was thinking something like this for the alpha banner, though it feels
> very stripe-y.
> [image: foia_alphabanner_1]
> <https://cloud.githubusercontent.com/assets/5911280/5685079/bd141bd6-97eb-11e4-9490-811bddec8a00.png>
>
> Perhaps to lessen that it could sit at the bottom of the browser window.
> Thoughts?
> [image: foia_alphabanner_2]
> <https://cloud.githubusercontent.com/assets/5911280/5685089/d1b38536-97eb-11e4-8df7-72ca4793c615.png>
>
> Also, not sure where 'Help us improve' would lead. Are you just having
> people email comments? Is it helpful to surface that in the banner?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/392#issuecomment-69378708>.
>



-- 
Jesse Taggert
Product Strategy, User Experience & Design
18F.gsa.gov

**Comment by khandelwal** [comment]
That color is a bit intense - enough so that it looks like a primary call to action. 

Regarding email addresses:  we can type it out, but also realize that if you right-click on an email address, the browser will say "Copy this email address". So that's another mode of interaction, in case typing out the email address is awkward.

I wonder if 'Help us improve' should go somewhere with a bit more information about how they can help us improve. With just the email address, it's unclear how users can help us. Also, I think we'd also like to hear when they really like what we've built.

**Comment by ericadeahl** [comment]
Here are some more minimal options. As discussed today, the banner will be static and will link to a section in "About this Project" that explains what alpha means, provides the email link, and explains what kind of feedback would be helpful.

![alphabanner_0113](https://cloud.githubusercontent.com/assets/5911280/5730980/ba8901e2-9b33-11e4-86b1-82867007ce9b.png)

![alphabanner_0113_2](https://cloud.githubusercontent.com/assets/5911280/5730938/602bc4fa-9b33-11e4-9b2f-05195f8d1766.png)

**Comment by khandelwal** [comment]
Second one above is the chosen one.

**Comment by rjmajma** [comment]
We determined the final iteration a week ago and referenced it in other threads. Considering this closed for the time being.
