### ISSUE TITLE
Design visual drop down search

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#393]

**Comment by ericadeahl** [comment]
@vz3 @jtag @rjmajma 

Here is a simple design for the drop down search. 

Is it important for the description of the agency to be included in the search suggestions? As it is now it feels like a lot of text to scroll through. I eliminated it here.

Also, playing around with the current version, the search suggestions do not always seem intuitive. Often agencies with the search word in their title are buried down the list of search suggestions, below agencies with the word in their description and others that seemingly have little relevance. I suggest that results with the search terms in their title be at the top of the list.

![foia_dropdownsearch](https://cloud.githubusercontent.com/assets/5911280/5684614/da1592aa-97e6-11e4-815e-21d2192c27f3.png)

Here's a second version with shortened agency descriptions included.

![foia_dropdownsearch-2](https://cloud.githubusercontent.com/assets/5911280/5684920/50910600-97ea-11e4-97f5-134414faf374.png)

**Comment by jtag** [comment]
I believe b/c search is also by keyword, so the desc is needed to show
where the keyword is hilighted in that text??

On Fri, Jan 9, 2015 at 10:31 AM, Erica Deahl <notifications@github.com>
wrote:

> @vz3 <https://github.com/vz3> @jtag <https://github.com/jtag> @rjmajma
> <https://github.com/rjmajma>
>
> Here is a simple design for the drop down search.
>
> Is it important for the description of the agency to be included in the
> search suggestions? As it is now it feels like a lot of text to scroll
> through. I eliminated it here.
>
> Also, playing around with the current version, the search suggestions do
> not always seem intuitive. Often agencies with the search word in their
> title are buried down the list of search suggestions, below agencies with
> the word in their description and others that seemingly have little
> relevance. I suggest that results with the search terms in their title be
> at the top of the list.
>
> [image: foia_dropdownsearch]
> <https://cloud.githubusercontent.com/assets/5911280/5684614/da1592aa-97e6-11e4-815e-21d2192c27f3.png>
>
> Here's a second version with shortened agency descriptions included.
>
> [image: foia_dropdownsearch-2]
> <https://cloud.githubusercontent.com/assets/5911280/5684920/50910600-97ea-11e4-97f5-134414faf374.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/393#issuecomment-69376869>.
>



-- 
Jesse Taggert
Product Strategy, User Experience & Design
18F.gsa.gov

**Comment by ericadeahl** [comment]
@vz3 For the small search bar:

![11 searchresults3](https://cloud.githubusercontent.com/assets/5911280/5749439/dd9d6a72-9bfd-11e4-9fe4-c6af0cf18214.png)

**Comment by rjmajma** [comment]
Hey @vz3 @khandelwal and @jtag, how do we feel about these designs Erica's proposed? Any feedback?

**Comment by rjmajma** [comment]
A few things: search has been changed to not include the agency description. That definitely saves us a lot of space. Some of these suggestions are no longer applicable, but I would like to consider playing around with the logic to surface the most likely relevant agency (e.g., searching for "Health" should probably make "Department of Health and Human Services" its first suggested agency).

**Comment by jtag** [comment]
I think cam be decided by V and E just talking it through. Design spike
ftw.

On Thursday, January 22, 2015, Raphael Majma <notifications@github.com>
wrote:

> A few things: search has been changed to not include the agency
> description. That definitely saves us a lot of space. Some of these
> suggestions are no longer applicable, but I would like to consider playing
> around with the logic to surface the most likely relevant agency (e.g.,
> searching for "Health" should probably make "Department of Health and Human
> Services" its first suggested agency).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/393#issuecomment-70972359>.
>


-- 
Jesse Taggert
Product Strategy, User Experience & Design
18F.gsa.gov

**Comment by rjmajma** [comment]
:+1:

**Comment by rjmajma** [comment]
Victor, Erica, and I just discussed. Logic issue is a separate issue and worth separating out. 

Closing this issue.
