### ISSUE TITLE
Implement unique visuals Search Results 

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#398]
@ericadeahl to quickly mock up

**Comment by ericadeahl** [comment]
@vz3 
![foia_searchresults](https://cloud.githubusercontent.com/assets/5911280/5688358/f9236310-980a-11e4-987f-414bcdeef078.png)

**Comment by khandelwal** [comment]
I must have missed something at some point. We have a search results page? Is there a way to get to it today? Or is this something we need to implement?

**Comment by konklone** [comment]
We do: https://foia.18f.us/agencies/?query=defense

But it's from a finite set of ~100 resources, so the pagination controls are going to be more trouble than they're worth for filtering through them.
