### ISSUE TITLE
Design wordmark or logo

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#401]

**Comment by ericadeahl** [comment]
Here are some logo sketches I did - all variations on the theme of searching documents, plus a circular "hub"

![foia_logo_011515-02](https://cloud.githubusercontent.com/assets/5911280/5903849/08aaa33a-a539-11e4-8d00-5d9de46940e7.png)
![logo1](https://cloud.githubusercontent.com/assets/5911280/5903851/0b5a82e4-a539-11e4-915f-89bd1731929f.png)
![logo2](https://cloud.githubusercontent.com/assets/5911280/5903852/0b6a91b6-a539-11e4-97ef-6ff1ba81ebc3.png)
![logo3](https://cloud.githubusercontent.com/assets/5911280/5903853/0b6dae82-a539-11e4-8179-e59cfc171afa.png)
![logo4](https://cloud.githubusercontent.com/assets/5911280/5903854/0b717abc-a539-11e4-99c3-0738a094def7.png)

**Comment by khandelwal** [comment]
- [ ] Pick a logo from the options above 
- [ ] Think about whether a name change is required

**Comment by jtag** [comment]
@ericadeahl 
Consider typeface choice and small opening of capital A (gets lots at smaller size) :)
Perhaps another iteration on magnifyig glass and icon to relate more, possibly interact, etc. 
Happy to talk more casually about it.

cheers!
Jesse

**Comment by jtag** [comment]
@ericadeahl Admittedly this story is low priority. Maybe another pass with focus on workdmark typeface? Logomark is bonus if you get to it.

**Comment by rjmajma** [comment]
Update: 
- Goal is to solely redesign the wordmark to open FOIA.

**Comment by jtag** [comment]
OpenFOIA,   Open FOIA,   OPEN FOIA, Open-FOIA .... in addition to wordmark,
how will it be written in text?

On Fri, Feb 20, 2015 at 8:21 AM, Raphael Majma <notifications@github.com>
wrote:

> Update:
>
>    - Goal is to solely redesign the wordmark to open FOIA.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/401#issuecomment-75265898>.
>



-- 
Jesse Taggert
Product Strategy, User Experience & Design
18F.gsa.gov

**Comment by rjmajma** [comment]
openFOIA is my preference (to match openFEC and openFDA).

**Comment by ericadeahl** [comment]
For now, let's use a simple Proxima wordmark and revisit logo design. 

I like openFOIA as a wordmark on its own but, thinking about how the mark would evolve, prefer the simplicity of Open FOIA or OPEN FOIA. Let's discuss.

![screen shot 2015-02-24 at 7 10 18 am](https://cloud.githubusercontent.com/assets/5911280/6351922/401a91b4-bbf4-11e4-900b-515725ebc2f5.png)

![screen shot 2015-02-24 at 7 07 36 am](https://cloud.githubusercontent.com/assets/5911280/6351871/ed55c96c-bbf3-11e4-87a3-be465d35be57.png)

**Comment by rjmajma** [comment]
Great stuff! I really like the top right one (openFOIA in blue and charcoal).

**Comment by jtag** [comment]
Moi aussi. Clean and can build on later.

On Tuesday, February 24, 2015, Raphael Majma <notifications@github.com>
wrote:

> Great stuff! I really like the top right one (openFOIA in blue and
> charcoal).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/401#issuecomment-75779072>.
>


-- 
Jesse Taggert
Product Strategy, User Experience & Design
18F.gsa.gov

**Comment by konklone** [comment]
Me too, the blue and charcoal in the top right. =)

**Comment by rjmajma** [comment]
Closing issue. Team decided with the top right one.
