### ISSUE TITLE
Reconsider storing foia_officer in the yaml files

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#406]
We don't display the this contact info on foia hub. Is it because the public shouldn't be contacting foia officers only foia liaisons? If so maybe we should remove it from the yamls.

**Comment by khandelwal** [comment]
Yes, I believe the FOIA officer is typically someone you would not contact - which is why we don't display that information. I think it's fine to leave it in the dataset (maybe someone else wants to do something with the information).
