### ISSUE TITLE
Carlsbad Field Office ? Waste Isolation Pilot Program not in final data

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#408]
`Carlsbad Field Office ? Waste Isolation Pilot Program` is on FOIA online, but not in our final data. It seems to be deleted in layer_with_csv.py 
Was it removed on purpose? If not, I can make sure it stays. 

Also we might to need to apply some more mapping for [full-foia-contacts.xls](https://github.com/18F/foia/blob/master/contacts/layering_data/full-foia-contacts.xls)

**Comment by ramirezg** [comment]
I've made an update to 18F/foia/pull/97 to solve this issue. Just need confirmation that we want to keep the office.

**Comment by khandelwal** [comment]
layer_with_csv shouldn't be deleting things. Can you look into that?

**Comment by khandelwal** [comment]
Also, we need to be insanely conservative with what we add to the manual data.

**Comment by ramirezg** [comment]
@khandelwal found the line and fixed it [here](https://github.com/18F/foia/pull/97/files#diff-08719b9d357973b49df3d5a0eca9b445R160)

**Comment by ramirezg** [comment]
18F/foia#97 should take care of this.

**Comment by ramirezg** [comment]
We found the missing office!
