### ISSUE TITLE
Add TTY numbers separately 

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#410]
make a new field in the yamls to store tty numbers

**Comment by khandelwal** [comment]
Does this involve changing the scraper to pull out the TTY numbers as well?

**Comment by ramirezg** [comment]
@khandelwal just checked for tty numbers they are only in EEOC, but don't seem to be different than any of the other numbers. Instead of making a new field I could just leave the tag in. Thoughts?

**Comment by khandelwal** [comment]
What's EEOC?
Also, what do you mean by leave the tag in?

**Comment by ramirezg** [comment]
It's the U.S. Equal Employment Opportunity Commission. And by 'leaving the tags in' I mean format the numbers as such: xxx-xxx-xxxx (TTY) whenever they are TTY instead of making an entirely new field.

**Comment by khandelwal** [comment]
In the multiple phone number case, I thought we had talked about displaying just one phone number. But  for TTY numbers, you'd want to display that separately. I think a new field would make that easier?

**Comment by ramirezg** [comment]
18F/foia/pull/99 is an option.
