### ISSUE TITLE
Search is inconsistent, and yields poor results

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#411]
There are several issues with the agency search. I think a number of them stem from the fact that we basically have two search implementations. A JavaScript based one, and a backend-Django based one. 

The JavaScript one kicks in to create a sort of autocomplete. 
The backend-one kicks in when you hit enter on the search button. 

Here are specific issues: 

1. Search for: 'department of defense'. It's an exact match for an agency name, but doesn't show up in the autocomplete results. It shows up lower down (which isn't useful)

2. Search for 'benzene'. You get results in the autocomplete. But type in 'benzene' and hit enter - now you don't get  any results back. 

3. Also, if you type in 'federal bureau of investigation' and hit enter, it will auto-direct to the FBI's landing page. But not if you try to use the autocomplete. I'd like to get rid of this last 'feature' as I think it's confusing. Thoughts @jtag, @ericadeahl and @vz3? 

The two types of search cause confusion and conflict. My vote would be have things behave a bit more consistently.

**Comment by ericadeahl** [comment]
Agreed that there should be more consistency between the autocomplete and the search results. Overall, the backend search implementation seems to be much more accurate/helpful than the autocomplete. The one improvement I'd like to see in the backend results is for agencies with the search terms in their titles to appear first in the results.

Re #3: If you remove this feature, when you search for 'federal bureau of investigation' you will get a search results page with one result, correct? I agree that would simplify things.

One other issue I noticed is that the names of sub groups/components are not showing up in search results. For example, "Department of Justice" page includes links to the "Office of Legal Policy" and "US Parole Commission" - but when I search for "parole" or "legal policy" I get no search results.

**Comment by cmc333333** [comment]
Autocomplete and search are slightly different beasts -- generally you want to autocomplete over a field with short, relatively dissimilar values. Full text search does a bit more analysis, think stop words, term vectors, porter stemming, and the like. I'd argue, then, that you don't really want an autocomplete if you're searching through agency descriptions (though it may be okay for keyterms). I've seen this implemented with an autocomplete over one field, with an option for "see more matches" or similar which will perform a full-text search.

I'd strong recommend using a search engine like elastic search or solr to handle both types of request (note that autocomplete fields are indexed differently) as that'll give you much more flexibility. You can tweak the result scoring metrics, add stop words, stemming, etc.

**Comment by khandelwal** [comment]
I just talked to @cmc333333 about search. Here are some notes from that conversation, and a way forward (that CM will work on). 

1. We're going to not use a search engine right now to do the search as it's probably prudent to stay away from making a major change like that right now. 

2. The autocomplete will autocomplete over agency names, and abbreviations. Giving autocomplete a smaller and well defined set of things to autocomplete over makes sense. 

3. Searching over descriptions, keywords etc. will happen either when you hit the search button, or when you click the last option in the autocomplete list. The last option in the autocomplete list will say something like 'search for your keyterms'. 

The behavior described above is approximately how the search in Gmail works, so it's a model users are familiar worth. 

@ericadeahl I'll make sure the backend search piece works as you describe.

**Comment by rjmajma** [comment]
cc @vz3 to make sure he hears this in case it has any other ramifications for the frontend.

**Comment by cmc333333** [comment]
An alternative which you might want to consider for the future is a Google Search approach, where the autocomplete is over *searched terms*. You'll need a lot more data before that's a viable option, though.

**Comment by khandelwal** [comment]
Yeah, that's what would make the most sense. But like you said, lots of data would be necessary for this.

**Comment by cmc333333** [comment]
This is also kind of confusing - on `/agencies/?query=XXX`, if you get only a single result, you are redirected to that agency's profile. This makes sense if you're searching for an agency's name, but is super confusing if you're using a generic term (I used "test")

**Comment by khandelwal** [comment]
Let's figure out if this can be closed or if there is pending work.

**Comment by khandelwal** [comment]
There are issues.

**Comment by rjmajma** [comment]
Issues are with typeahead. When users click on something, it should let them go to the appropriate landing page. 

cc @vz3

**Comment by rjmajma** [comment]
Closing. Will add this to QA testing.
