### ISSUE TITLE
Design Tablet/Mobile view

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#416]
@vz3 Here are tablet and mobile versions.

For tablet, the type and layout are pretty much the same as the desktop version, except:
- the homepage is 1 column narrower
- on the agency detail page, the side bar with the contact details moves under the agency description.

Tablet: home
![tablet home](https://cloud.githubusercontent.com/assets/5911280/5768123/d026ca44-9cc2-11e4-9416-050d5e5f5441.png)

Tablet: agency page
![tablet agency detail](https://cloud.githubusercontent.com/assets/5911280/5768125/d2f5c5f4-9cc2-11e4-9010-7f45e77fc2f7.png)

On mobile:
- the type sizes are all the same except for the 36px titles, which are reduced to 24px.
- I mocked up a menu that opens to the side, and the alpha message is in there (when I tried it at the top of the page along with the “official government site” message it seemed like a ton of text - does that seem ok to people?) 
- I tried to mimic the search functionality we have on the desktop version. There is a large search bar on the homepage, but on all other pages there is a search icon in the header. When you click it the search bar opens beneath the header. Thoughts/suggestions on how this is working? @jtag 

Mobile: home
![mobile home](https://cloud.githubusercontent.com/assets/5911280/5768139/e986f0ae-9cc2-11e4-8cc9-2e787352f00f.png)

Mobile: menu
![mobile menu](https://cloud.githubusercontent.com/assets/5911280/5768143/f1107fac-9cc2-11e4-8ea0-e1ddda28545e.png)

Mobile: agency page
![mobile agency detail](https://cloud.githubusercontent.com/assets/5911280/5768152/01480da4-9cc3-11e4-99fe-e4c740078594.png)

Mobile: open search bar
![mobile search](https://cloud.githubusercontent.com/assets/5911280/5768148/f67595cc-9cc2-11e4-91ca-bcb24f64bfa6.png)

**Comment by rjmajma** [comment]
Hey @vz3 @khandelwal and @jtag, how do we feel about these designs Erica's proposed? Any feedback?

**Comment by rjmajma** [comment]
Mobile view looks great. A few thoughts. 

Do we care more about the "official website" language or the "alpha" banner language?

Also, would it be helpful to limit the number of search results the user sees when searching on mobile? That way we don't take up the whole screen before sending users off to a search results page?

**Comment by rjmajma** [comment]
Victor, Erica, and I discussed. We aren't limiting the number of search results and keeping "official website" for the time being. 

Closing this issue.
