### ISSUE TITLE
Make it easy for external folks to help

### ISSUE THREAD

**Issue by nsinai** [18F/foia-hub#417]
Maybe add a tag so relative newbies to the projects can scrub in?  Maybe add something to the read me as well explaining how folks new to github and FOIA can find ways to participate?

**Comment by istanfield09** [comment]
I check the issues page several times a week, and would love to have the opportunity to contribute more. Using the 'help wanted' tag more often would be cool, otherwise sometimes I feel like I am stepping on other's toes. I'm always willing to do the grunt work! : )

**Comment by konklone** [comment]
Thank you, @istanfield09 - it's very motivating to get comments like that. =) We should definitely start using `help wanted` more (and across our projects).

For what it's worth, on this 18F project in particular, we tend to be pretty good about formally assigning issues to the people who are responsible for getting them done over the next week or two (in a particular sprint), so unassigned issues are relatively likely to be up for grabs.

**Comment by rjmajma** [comment]
All good points, as usual @nsinai. I've added a "help wanted" tag that we'll have to take some time to determine what is relatively easy for folks not entrenched in the project to pick up. 

And thanks, @istanfield09. Thanks for checking and being so interested. We'll do a better job of making sure you and other interested folks have stuff to contribute on. Thanks for your patience (and enthusiasm!).

**Comment by nsinai** [comment]
Well said @istanfield09!  @konklone and @rjmajma -- thanks for creating & regularly using the Help Wanted tag.  This will be good to revisit in a month or two, to see what kind of community activity is generated from that tag.  Will we have the ability to quickly do that analysis?

I totally get that lean/agile is focused on short sprints, and issues/tasks are prioritized and assigned, or moved out of the sprint.  But what if 10 people wanted to help?  What if 100 people? 1,000?

Are there issues you need research on, but aren't a near term problem?

**Comment by khandelwal** [comment]
When you start getting to 10, 100, 1000 people regularly helping the project management would take a different approach. I imagine sprint planning would look very different (we'd identify a couple different tracks that need work, and spend a lot more time spelling out the work in each).

One could also imagine that the effort in general would look very different (we'd step back and try and solve multiple problems at once), and we'd consider building out: a dropbox for agency records, or better redaction tools, or explore building FOIA centric eDiscovery platforms.With a 100 people working on a project - the scope of what we could accomplish would greatly increase. However, each team would work the same way as we do now. 

What you're getting at with some of your questions is the notion of managing online open source communities. I personally haven't given it much thought. So, here's to a 100 person group of collaborators.
