### ISSUE TITLE
Fix License issues

### ISSUE THREAD

**Issue by cmc333333** [18F/foia-hub#418]
I see that libraries are now being distributed with the project (specifically in `node_modules`). These libraries don't fall under the public domain + CC0 license, so we need to add exceptions in the root LICENSE file.

**Comment by rjmajma** [comment]
Good call! I'll assign myself to this.

**Comment by vz3** [comment]
What are we using Node for?

**Comment by konklone** [comment]
This was fixed by #450. We also removed `node_modules` from the repo - they're now installed on demand during the deploy process.

@vz3 It's for the deployment webhook, which is Node-based. We may end up ditching this too as we move to 18F's new PaaS.

**Comment by khandelwal** [comment]
Can this be closed?

**Comment by konklone** [comment]
Yep.
