### ISSUE TITLE
Design a favicon for FOIAHub

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#429]

**Comment by ericadeahl** [comment]
Here are 2 options, 16x16 and 32x32. This can be updated if we develop a logo.

![foiafavicon_1_16x16](https://cloud.githubusercontent.com/assets/5911280/6538679/1a0670f0-c41a-11e4-821f-48773b879885.png)


![foiafavicon_1_32x32](https://cloud.githubusercontent.com/assets/5911280/6538678/1a04bba2-c41a-11e4-90af-112dcb1c7582.png)


![foiafavicon_2_16x16](https://cloud.githubusercontent.com/assets/5911280/6538680/1a07653c-c41a-11e4-9894-4b0b69148c1b.png)


![foiafavicon_2_32x32](https://cloud.githubusercontent.com/assets/5911280/6538677/1a049f5a-c41a-11e4-803d-122088cf7a19.png)

**Comment by vz3** [comment]
The F is really cool!

**Comment by konklone** [comment]
Big :heart: for the F, that is much more branded and interesting and distinctive.
