### ISSUE TITLE
Check Stats Data for Inconsistencies

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#433]
- [x] Record missing simple and complex medians
- [x] Record instances of reversed simple and complex medians.
- [x] Find source of inconsistencies.

**Comment by ramirezg** [comment]
##### [List of all the inconsistencies](https://gist.github.com/ramirezg/f5f2062ff20056ad4743)

##### Office Level Issues
missing complex processing time: 75
missing simple processing time: 19
missing both processing times: 64
'reversed' processing times: 32

##### Agency Level Issues
missing complex processing time: 26
missing simple processing time: 3
missing both processing times: 5
'reversed' processing times: 3

I'm going through the these lists to determine the source of the issues. So far it appears to be the data on foia.gov/data, but just to make sure I'll check at least 25 or so.

**Comment by rjmajma** [comment]
Once you find the source of the inconsistencies, please send me another email on that one. I'd like to have these all in one place.
