### ISSUE TITLE
KRANG: Interview 3 DOJ FOIA officers to better understand how they process requests and share responsive records

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#438]
- [x] Interview 1
- [x]  Interview 2
- [x]  Interview 3
- [x]  Notes and synthesis

**Comment by jtag** [comment]
Re First Interview (OIP)
@vz3 and @khandelwal Would you have bandwidth to either drop your raw notes in here and/or focus on the top portions of this doc. especially responsive records, pain points, and opportunities? Otherwise I can extrapolate from our post board exercise end of that day. 

Google doc: https://docs.google.com/a/gsa.gov/document/d/1ScjfU5jDAl3RHE6UZuOPrwHubIdLyKraNwvJjR4862s/edit#

**Comment by rjmajma** [comment]
@ericadeahl will transcribe the last set of notes today. 

This work will translate to journey map and personas.

**Comment by jtag** [comment]
@vz3 Do you have raw notes to drop into a doc? I'm happy to add mine, but I was facilitating that day. My goal is to  help close this story for Friday.

**Comment by ericadeahl** [comment]
All notes in. Closing!
