### ISSUE TITLE
KRANG: Audit DOJ FOIA reading rooms to better understand info architecture, quantity, and nature of documents there

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#442]

**Comment by jtag** [comment]
Possibly synthesis in Murally

**Comment by jtag** [comment]
Victor and Gabriel started spreadsheet

**Comment by jtag** [comment]
@vz3 @ramirezg @khandelwal In the library audit spreadsheet https://docs.google.com/a/gsa.gov/spreadsheets/d/1ckOys_i-8rh5uYC40OaFAFo1mKROuuPD_qKTgAgKBk0/edit#gid=0

Shouldn't we also include if meta data includes original document type?  For instance I assume someone searching on subject X would be able to refine their search knowing if the record were an email, press release, calendar item, etc.

Put another way, does knowing  if current FOIA Libraries/Proactive docs include this help us build a better search?

**Comment by jtag** [comment]
Goal of audit:
-What are the opportunities and challenges of hooking into current DOJ FOIA Libaries/Reading Rooms for search and possible record landing pages?
-What might we discover by looking at every one of these?

**Comment by ramirezg** [comment]
Spreadsheet is complete.

**Comment by jtag** [comment]
@vz3 @ramirezg Great you completed this! What are the take aways you two gleaned by doing this? Thing of what to share during mid-sprint review Wed? 

What expectations were met or surprises?

**Comment by khandelwal** [comment]
It would also be great for you to add your take-aways here for documentation purposes.

**Comment by ramirezg** [comment]
Notes: 
1. Few DOJ agencies have comprehensive FOIA responses, logs, and preemptive disclosures.
2. With the exception of the FBI no DOJ agencies have search.
3. Scanned PDF might present a problem because text detection varies in accuracy.
