### ISSUE TITLE
KRANG: Create simple personas of a FOIA Requestor 

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#443]

**Comment by jtag** [comment]
store in murally

**Comment by ericadeahl** [comment]
Personas are here: https://mural.ly/t/gsa6/m/gsa6/1423515818233

![screen shot 2015-02-25 at 11 22 05 am](https://cloud.githubusercontent.com/assets/5911280/6378519/ce43d40e-bce0-11e4-8595-4713cd127abf.png)
![screen shot 2015-02-25 at 11 22 37 am](https://cloud.githubusercontent.com/assets/5911280/6378523/d4564160-bce0-11e4-9a92-ba55f4f9db25.png)

**Comment by khandelwal** [comment]
These are fantastic.
