### ISSUE TITLE
Research Technologies

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#444]
Learn about and try out
- [ ] [Haystack] (http://haystacksearch.org/)
- [ ] [ElasticSearch server] (http://www.elasticsearch.org/)

**Comment by rjmajma** [comment]
Awesome work on this so far!

**Comment by cmc333333** [comment]
LMK if you run into anything; I've set these up a few times now -- should be smooth sailing for you.

**Comment by ramirezg** [comment]
@cmc333333 , actually I'd love to pick your brain about customizing haystack in a day or so.

**Comment by ramirezg** [comment]
Added notes to a [mock app](https://github.com/ramirezg/mock_haystack_app/), and also found that we could use haystack to import documents, but later query with a lower-level library like [elasticsearch-py](http://www.elasticsearch.org/guide/en/elasticsearch/client/python-api/current/) for [example.](https://github.com/ramirezg/mock_haystack_app/blob/master/mockapp/views.py#L6)
