### ISSUE TITLE
Duplicated foia libraries

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#445]
https://foia.18f.us/contacts/department-of-justice--tax-division
Both libraries have the same url.

**Comment by ramirezg** [comment]
Also, https://foia.18f.us/contacts/department-of-justice--office-of-the-inspector-general

**Comment by khandelwal** [comment]
Huh. I'm pretty sure there was code that eliminates this. I'll take a look.

**Comment by ramirezg** [comment]
@khandelwal the urls might be slightly different, but they goto the same place

**Comment by khandelwal** [comment]
Ugh. I've seen all this before. A cleaner, more useful fix will come soon.

**Comment by khandelwal** [comment]
Both examples no longer have issues based on new loading code that's in place.
