### ISSUE TITLE
Allow searching by agency abbrevation

### ISSUE THREAD

**Issue by polastre** [18F/foia-hub#449]
I would like to search for "CBP" or "CIS", because I don't know the full name of the agency (Customs and Border Protection).

**Comment by polastre** [comment]
Examples:

CBP doesn't work:
![screen shot 2015-01-28 at 3 40 44 pm](https://cloud.githubusercontent.com/assets/2539570/5949572/0dd90ba4-a704-11e4-871b-6503cc5d0f89.png)

Customs does:
![screen shot 2015-01-28 at 3 40 49 pm](https://cloud.githubusercontent.com/assets/2539570/5949574/13f19ad8-a704-11e4-899f-e6a1167cfebb.png)

**Comment by jpyuda** [comment]
Note that this _does_ work for things like CFPB. So it seems like the dataset just needs to be expanded.

**Comment by rjmajma** [comment]
Yup, this is a data source problem. @ramirezg, any idea why other acronyms aren't being included?

**Comment by cmc333333** [comment]
https://github.com/18F/foia-hub/blob/master/foia_hub/scripts/load_agency_contacts.py#L178

Should probably only call that if the data set doesn't have an abbreviation specified

**Comment by ramirezg** [comment]
@cmc333333 good catch, we've been overwriting our abbrevation this entire time.

**Comment by ramirezg** [comment]
Fixed with 18F/foia-hub/pull/452

**Comment by ramirezg** [comment]
@konklone, looks like the realtime search isn't working yet. Do we need to reset the node module?

**Comment by konklone** [comment]
The automatic _data loading_ proceeds on its own schedule, I think -- @cmc333333 set that part up. (I know, it should probably auto-update data on deploy too.) Can coordinate with the both of you off-thread.

**Comment by cmc333333** [comment]
IIRC, data loading happens when the data changes (specifically, when the `foia` repo is out of date). You can definitely reload all the data at will, though, too.
