### ISSUE TITLE
add link to github issues

### ISSUE THREAD

**Issue by gbinal** [18F/foia-hub#461]
Looking at [the site](https://foia.18f.us), there's a feedback mechanism but it's an email address.  Wouldn't it be better to link to the github issues for this project?

**Comment by konklone** [comment]
For the [`/developer` section](https://foia.18f.us/developers), yeah (though that page is a mess). I personally wouldn't feel comfortable putting a GitHub issue tracker as the general feedback mechanism for a government site aimed at the general public.

**Comment by ramirezg** [comment]
Added on  18F/foia-hub/pull/478

![screen shot 2015-02-11 at 4 16 08 pm](https://cloud.githubusercontent.com/assets/4596845/6156572/6329ccb4-b209-11e4-8d64-7c24d2bd9cc0.png)

**Comment by gbinal** [comment]
Rock.

**Comment by ramirezg** [comment]
closed with 18F/foia-hub/pull/478
