### ISSUE TITLE
Add a /developer page

### ISSUE THREAD

**Issue by gbinal** [18F/foia-hub#462]
If there are APIs underneath the foia hub, it'd be very helpful to add a developer hub at foiahub.biz/developer.  To facilitate 3rd party re-use, it'd be important to link to a /developer page.

**Comment by konklone** [comment]
It is there (and a mess), but we foolishly [pluralized it](https://foia.18f.us/developers).

**Comment by khandelwal** [comment]
It's a mess because we haven't gotten around to implementing the new designs. 

It's fairly common (and not so foolish) to pluralize the developer pages. See: 

https://developers.facebook.com/
https://www.tumblr.com/developers/
http://www.data.gov/developers/

**Comment by gbinal** [comment]
> It's fairly common (and not so foolish) to pluralize the developer pages. 

Totally agree.  That said, I strongly recommend that agencies ensure a redirect for whichever one they don't use, so that x.gov/developer and x.gov/developers always works.  I'll create a new issue to that effect.
