### ISSUE TITLE
Add descriptions to all top-level agencies

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#463]
Find out why these descriptions don't exist and or update them with real text. 

![screen shot 2015-02-03 at 1 42 06 pm](https://cloud.githubusercontent.com/assets/4596845/6026642/7688c75c-abaa-11e4-9549-23f7f64acd5e.png)

**Comment by khandelwal** [comment]
Make sure that getting these descriptions is automated. Not an update to manual files. Also, remember that descriptions are something that will come through as part of the contact update process.

**Comment by ramirezg** [comment]
Just found the issue and submitted a [PR](https://github.com/18F/foia/pull/103)

Also, food for thought. I realized we could probably add more office descriptions; however, due to the our agency/office hierarchies and special office names, it would take some degree of detailed mapping work.

**Comment by ramirezg** [comment]
Solved with 18F/foia/pull/103

**Comment by khandelwal** [comment]
![screen shot 2015-02-19 at 10 37 33 am](https://cloud.githubusercontent.com/assets/636752/6269759/5631256e-b823-11e4-84a4-5f78462478b5.png)
