### ISSUE TITLE
508 Accessibility Check pre-launch

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#466]
We should check the current app with Nick Bristow.

cc @vz3

**Comment by vz3** [comment]
Notes from the review:

```Issues
Color Contrast
Placeholder text in search box

- Give your tabs a role='tab' and the active one aria-selected='true'

- Add a skip nav link to the beginning of the page, see http://18f.github.io/accessibility/links/

- For your anchor links, give their targets a tabindex='-1' so when you're using a keyboard, you can select one then continue tabbing from that point. (a-z, faq)

- Add aria-label to your search field with the placeholder text. 

- Add a proper label for the search field, <input id='search'></input><label for='search'><span class='sr-only'>Search</span></label> 

Something like that would be great.

-Add Alt text to 18f Logo. 

- set 'lang="en"' for the page in the <html> 

- Focus should be more discernable, check the link after search

- check this for aria tags for auto complete, not 100% necessary but it would make it a lot more accessible https://webaccessibility.withgoogle.com/unit?unit=6&lesson=13```

**Comment by vz3** [comment]
Issues
- [ ] Color Contrast
- [ ] Placeholder text in search box
- [ ] Give your tabs a role='tab' and the active one aria-selected='true'
- [ ] Add a skip nav link to the beginning of the page, see http://18f.github.io/accessibility/links/
- [ ] For your anchor links, give their targets a tabindex='-1' so when you're using a keyboard, you can select one then continue tabbing from that point. (a-z, faq)
- [ ] Add aria-label to your search field with the placeholder text. 
- [ ] Add a proper label for the search field, <input id='search'></input><label for='search'><span class='sr-only'>Search</span></label> 
- [ ]Add Alt text to 18f Logo. 
- [ ] set 'lang="en"' for the page in the <html> 
- [ ] Focus should be more discernable, check the link after search
- [ ] check this for aria tags for auto complete, not 100% necessary but it would make it a lot more accessible https://webaccessibility.withgoogle.com/unit?unit=6&lesson=13
