### ISSUE TITLE
Krang: Create Simple Persona of a FOIA Processor

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#467]

**Comment by ericadeahl** [comment]
personas are here: https://mural.ly/t/gsa6/m/gsa6/1423515818233

![screen shot 2015-02-25 at 11 22 28 am](https://cloud.githubusercontent.com/assets/5911280/6378503/acd892dc-bce0-11e4-90d5-07244590764a.png)

**Comment by jtag** [comment]
awesome!

On Wed, Feb 25, 2015 at 2:23 PM, Erica Deahl <notifications@github.com>
wrote:

> Closed #467 <https://github.com/18F/foia-hub/issues/467>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/issues/467#event-241959733>.
>



-- 
Jesse Taggert
Product Strategy, User Experience & Design
18F.gsa.gov
