### ISSUE TITLE
Fix matching in FOIA data, and use real usa.gov API

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#470]
Our agency name matching is manually controlled. 
We could try write some heuristic-based functions to better do this (and not have it be based on lookups). 

Additionally, we currently use a .json file that's the result of some sort of usa.gov api query to populate descriptions. Let's just use the live query instead (so that we have the latest information).

**Comment by ramirezg** [comment]
Solved with 18F/foia/pull/103
