### ISSUE TITLE
On the agency landing page, change the order under 'submit a request'

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#475]
The current order is: 

1. request online
2. request by mail
3. request by email
4. request by fax

This should (probably) be changed to: 

1. request online
2. request by email
3. request by fax
4. request by mail

The second, newer order makes more sense as it's in decreasing order of technology.

**Comment by khandelwal** [comment]
![screen shot 2015-02-10 at 10 13 24 am](https://cloud.githubusercontent.com/assets/636752/6129584/7d87a8e4-b10d-11e4-9b74-b85db8627e00.png)

**Comment by rjmajma** [comment]
+1 to this change. Thanks for catching it.

**Comment by ramirezg** [comment]
changed on  PR #478
