### ISSUE TITLE
/learn directs users to foia.gov for public liaison contact - but we have that in foia-hub

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#476]
On /learn we say: 

"Contact information for every agency's FOIA public liaison is listed on www.foia.gov" 

but we have that information on foia-hub now. So we should instead direct them to our tool.

**Comment by khandelwal** [comment]
![screen shot 2015-02-10 at 10 14 11 am](https://cloud.githubusercontent.com/assets/636752/6129623/c222abf2-b10d-11e4-92d2-1a52f2c75847.png)

**Comment by rjmajma** [comment]
Another good catch. Make it so.

**Comment by ramirezg** [comment]
So just redirect to https://foia.18f.us/agencies/ ?

**Comment by rjmajma** [comment]
I would change it to, "information for every agency's FOIA Public LIaison is listed on their respective agency or component page on https://foia.18f.us/agencies."

**Comment by ramirezg** [comment]
Changed to the wording below on PR #478
![screen shot 2015-02-10 at 10 55 39 am](https://cloud.githubusercontent.com/assets/4596845/6130527/9cb64300-b113-11e4-8806-b2ae8dd4b9d1.png)

**Comment by rjmajma** [comment]
Rock. Thanks, @ramirezg.

**Comment by ramirezg** [comment]
closed with 18F/foia-hub/pull/478
