### ISSUE TITLE
List of agencies page current implementation still needs to match the design

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#477]
This is the design:

![screen shot 2015-02-10 at 10 28 40 am](https://cloud.githubusercontent.com/assets/636752/6129933/be8d9842-b10f-11e4-9928-5c0074d75a49.png)

**Comment by khandelwal** [comment]
This is the current implementation

![screen shot 2015-02-10 at 10 30 12 am](https://cloud.githubusercontent.com/assets/636752/6129942/d38fd9ee-b10f-11e4-9125-a27d5a0b6247.png)

**Comment by khandelwal** [comment]
The two things that seem to be missing are: 

- [ ] styling for the letters that precede the list of agencies starting with that letter
- [ ] a back to top link

The font weights don't seem to be the same either, but I think that's covered elsewhere.

**Comment by vz3** [comment]
This is in PR #612

**Comment by vz3** [comment]
Merged above. Closing.
