### ISSUE TITLE
Revisit API documentation

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#479]
Let's revisit our API documentation and ensure it's useful, helpful and covers all the latest changes to the API endpoints. We've tried to keep this updated, but it's worth doing a quick check. 

Here's where the API documentation is listed: 
http://foia-hub.readthedocs.org/en/latest/

We'll know this task is complete when the API documentation has been updated to reflect the current state of affairs. For example, the request API documentation should probably be removed as we're very far from that being a reality.

**Comment by ramirezg** [comment]
18F/foia-hub/pull/654
