### ISSUE TITLE
Get a .gov domain

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#480]
Our FOIA contacts stuff is close to being ready for release to the public. We should get a .gov domain as this lends credibility to our effort and let's the user know that the data and information comes from the United States Government. 

This task as two components for success: 

- [ ] Create a list (in this task) of all the steps required to actually get a .gov domain
- [ ] Check off that list, and have at least a test version of our site running of the new .gov domain. 

It might be likely that we split this up into multiple issues, but here's to hoping getting a .gov domain isn't actually all that difficult.

**Comment by konklone** [comment]
Once the decision has been made by the program office in charge of the parent domain, we'l follow [the Amazon procedure](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html) to fully "delegate" the subdomain to Route 53's infrastructure. We're then free to make, modify, and remove CNAME/A/TXT/MX records at will. It's a requirement of how 18F works -- just getting a CNAME from the parent domain, that they manage in their infrastructure, will _not_ be enough. We have ample precedent for doing this, and I'm happy to take point on whatever DNS conversations are necessary.

**Comment by rjmajma** [comment]
Have tentative approval for two .gov subdomains. Will update once firmed up. Will document the process once the process has been identified :shrug:.

**Comment by nsinai** [comment]
Shouldn't this be at DOJ or Foia.gov?

**Comment by konklone** [comment]
@nsinai We're working out a few options.

**Comment by khandelwal** [comment]
Do we have a process yet?

**Comment by konklone** [comment]
@rjmajma Once we know the subdomain(s) we want, we can create the Hosted Zone inside our infrastructure, and generate the records that the parent domain owner will need to set.

- [ ] Pick the subdomain, or subdomains, for which we will be requesting delegation.

**Comment by konklone** [comment]
```
$ dig open.foia.gov NS

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> open.foia.gov NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60260
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;open.foia.gov.			IN	NS

;; ANSWER SECTION:
open.foia.gov.		600	IN	NS	ns-1665.awsdns-16.co.uk.
open.foia.gov.		600	IN	NS	ns-454.awsdns-56.com.
open.foia.gov.		600	IN	NS	ns-513.awsdns-00.net.
open.foia.gov.		600	IN	NS	ns-1365.awsdns-42.org.

;; ADDITIONAL SECTION:
ns-1665.awsdns-16.co.uk. 28922	IN	A	205.251.198.129
ns-454.awsdns-56.com.	28313	IN	A	205.251.193.198
ns-513.awsdns-00.net.	27846	IN	A	205.251.194.1
ns-1365.awsdns-42.org.	27677	IN	A	205.251.197.85

;; Query time: 396 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Mar 16 14:55:24 EDT 2015
;; MSG SIZE  rcvd: 246
```
