### ISSUE TITLE
Negotiate another corpus of documents for search

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#481]
Let's find an agency who's willing to provide us with a useful corpus of documents to include in our search. 

Useful is a hard to measure concept, but we can perhaps agree that most reading rooms contain employee handbooks and FOIA logs. Those aren't the same usefulness as a corpus of documents on a particular subject of interest to the public. 

This will be complete when we have an agreement from the agency to look for documents, and an agreement make those available through our search site (Krang)

**Comment by ramirezg** [comment]
@khandelwal What about the document that we already have access to will we include those in the MVP as well?

**Comment by khandelwal** [comment]
We've talked repeatedly about going out with a curated set of documents initially. Interesting enough for people to pay attention to our site.

**Comment by rjmajma** [comment]
Reached out to friends. Will reach out to more on Tuesday.

**Comment by rjmajma** [comment]
Still working on this. Reached out to more colleagues.

**Comment by rjmajma** [comment]
This experiment didn't work. Closing this for now.

Other possible attempts can be: 
 - Offer agencies a reading room on our site
 - Publicize on our site that we are accepting documents
