### ISSUE TITLE
Outline a blog post for the release of our contacts information

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#482]
To get the blog post rolling, let's create an outline for the post that'll accompany our small release to the public. It depends on what we want to talk about, but one of the things could be how much effort (and what efforts) went into trying to ensure the FOIA contacts information is accurate. 

This is complete when there is an 

- [x] outline for a blog post in this issue.

**Comment by khandelwal** [comment]
This also includes: 

- [ ] Linking up with the comms and content team.

**Comment by rjmajma** [comment]
Comms team is thoroughly looped in. We'll have to discuss with legal and leg. affairs as well, but that's already a part of the comms process.

**Comment by rjmajma** [comment]
Outline is more than complete. We'll likely have something that feels closer to complete before the end of the sprint with some internal GSA sign off. 18F content team is already killing it.

**Comment by khandelwal** [comment]
Where's the outline?

**Comment by nsinai** [comment]
+1 Would be great to see the outline!

**Comment by khandelwal** [comment]
Since my last comment was posted 4 days ago, I've learned that we actually have a first draft of the blog post. Unfortunately it's now in the comms process and I don't think we can post it here before it's all been approved. 

I'd love to see a post from you in the works @nsinai that talks about why this project is important and what you hope to see it accomplish.

**Comment by rjmajma** [comment]
Spoke to the content team yesterday. We're in good shape. Closing!
