### ISSUE TITLE
Build reusable Document Processing toolkit

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#486]
We'll need create a util script to help us convert PDF to text. Based on research from #473, it should use Tika for responsive documents, but shift to Tesseract when a document has not been properly ORCrd.

**Comment by khandelwal** [comment]
This task is complete when we have created an independent Python library to extract text from PDF, and default to OCR when text extraction fails. This library will be independent because there is talk of it being shared by other efforts across 18F.

**Comment by ramirezg** [comment]
Started a [repo](https://github.com/18F/doc_processing_toolkit). Currently, it has all the basic functions:
- pdf to text
- pdf to img to text (for OCRing)
- uploading to S3

The script heavily depends on [subprocess](https://docs.python.org/3/library/subprocess.html) because most of the tool for changing images are in C or Java. Also, many of the Python connectors are outdated or too broad in scope. One option that might work for OCR is [pypdfocr](https://github.com/virantha/pypdfocr).

TODO
- research methods to determine if a doc has been ocr'd
- combine functions properly.

**Comment by khandelwal** [comment]
Having this be a pull request would have been very useful.

**Comment by ramirezg** [comment]
So far word length has been a decent way of determining if a document needs to be OCR'd, but I'm continuing to research other methods.  

Unfortunately, I've discovered that spreadsheets seem to be the most troublesome and slow doc type to convert.

**Comment by khandelwal** [comment]
We've created a first pass at the independent library. We're now working on using it and integrating it with Krang, but I feel like that's a separate issue.
