### ISSUE TITLE
Use an S3 bucket to store static assets 

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#489]
For the existing contacts application, we need to store the static assets in an S3 bucket. Let's create an S3 bucket to store those assets, and use that moving forward. 

This task is complete when: 
- [x] We document how we are dealing with static assets currently 
- [x] We setup an S3 bucket (tagged appropriately) for storing static assets
- [ ] We use that S3 bucket to serve static assets.

**Comment by cmc333333** [comment]
Note that django storages doesn't have py3 support, but a fork does: https://github.com/18F/peacecorps-site/blob/master/requirements.txt#L23

**Comment by ramirezg** [comment]
DevOps is getting the buckets setup 18F/DevOps/issues/239

**Comment by rjmajma** [comment]
Team DevOps killed it. S3 buckets are set up. https://github.com/18F/DevOps/issues/239#issuecomment-74162002

Thanks @ozzyjohnson!

**Comment by khandelwal** [comment]
Buckets don't have the right permissions.

**Comment by khandelwal** [comment]
@ramirezg Where are we with the buckets that were created for us? Do they work with your permissions?

**Comment by khandelwal** [comment]
Add environment variables to cloud foundry.

**Comment by khandelwal** [comment]
So, I added the correct environment variables to cloud foundry apps foia-a and foia-b. Since environment variables persist, these will be available for when we start using the production settings file.
