### ISSUE TITLE
Use an S3 bucket to store and serve documents

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#490]
We need to use an S3 bucket to store the documents we have indexed and provide through search. 

This task is complete when: 
 - [x] We create an S3 bucket
 - [x] We change our document import scripts to move the documents into the bucket
 - [x] We use the S3 bucket to serve documents

**Comment by ramirezg** [comment]
DevOps is working on getting the buckets up 18F/DevOps/issues/239

**Comment by khandelwal** [comment]
I've worked on changing our document import scripts to move the documents into an S3 bucket. I'm working off a personal bucket right now, and once we have authentication/permission things figured out we can use the official bucket. A related pull request will be there soon.

**Comment by khandelwal** [comment]
@ramirezg Did you get anywhere with trying to use the official buckets?

**Comment by ramirezg** [comment]
Unfortunately, no. It's a permissions issues, which DevOps is working on. I've pasted the error backtrace in 18F/DevOps/issues/242

**Comment by khandelwal** [comment]
How are we doing with permissions? Is this resolved?

**Comment by ramirezg** [comment]
@khandelwal So we've both tested s3 for Krang on our personal accounts, but my permission are more restricted than ever now. 
![screen shot 2015-03-03 at 12 06 22 pm](https://cloud.githubusercontent.com/assets/4596845/6467684/e1431940-c19d-11e4-94d4-5e52c9297710.png)

If we need to, we can just use @konklone's credentials for deployment.

**Comment by konklone** [comment]
@ramirezg This isn't fixed? I can resolve this at any point, we worked out a solution with @ozzyjohnson.

**Comment by ramirezg** [comment]
@konklone we can close this ticket once we have the credentials from https://github.com/18F/foia-hub/issues/584 working

**Comment by khandelwal** [comment]
So, where are we with this? Do we have the personal accounts working? If we do, we can close this and leave 584 open.

**Comment by ramirezg** [comment]
@khandelwal yeah, let's close it.

**Comment by khandelwal** [comment]
So this is working for you with the 18F bucket?

**Comment by khandelwal** [comment]
I think I might have mis-spoke earlier. This can be closed when this works with the 18F buckets. That way we know we know what permissions to setup.

**Comment by ramirezg** [comment]
Krang staging is now using 2 buckets
