### ISSUE TITLE
Change Django/application settings to use environment variables

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#491]
Currently we use a local_settings.py file to contain settings such as database connection information. Let's change that to use environment variables. 

This task is complete when: 

- [ ] All settings that need to be changed per development, staging, production are now stored in environment variables
- [ ] We evaluate whether we want to keep the current local_settings.py mechanism, or just use something like autoenv and move to environment variables completely. 
- [ ] Change the README.md to reflect changes.

**Comment by cmc333333** [comment]
Something that's worked well for us on peacecorps is to continue to separate vars into `production`, `dev`, etc. settings files, but use env vars to switch between them (`DJANGO_SETTINGS`). This probably wouldn't make sense between staging and production, though.

**Comment by khandelwal** [comment]
This pull request makes some settings into environment variables https://github.com/18F/foia-hub/pull/512/files and encourages the use of autoenv.
