### ISSUE TITLE
Stats on FOIA docs

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#496]
Get average file size, number of pages, number of words etc.

**Comment by ramirezg** [comment]
File size stats in megabytes. For 1551 PDFs files from foiaonline. Basically, 90% of the files are under 2.6 MB only the top 3% are over 10 MB. 
```
count  1551.000000
mean      2.362045
std      15.863666
min       0.006238
10%    0.033323
20%    0.054176
30%    0.082924
40%   0.131223
50%    0.233996
60%    0.327602
70%    0.543010
80%    1.125667
90%    2.640414
max     277.032406
```

**Comment by ramirezg** [comment]
Stats on document number of words for 1559 documents. (Words defined combinations of 3 letter chars or more).  Documents with 0 words either are pictures with no text or have not been properly ORCrd.  
```bash
count     1559.000000
mean      3514.287364
std      32927.348021
min          0.000000
25%         81.000000
50%        269.000000
75%        745.000000
max    1142653.000000
```

**Comment by khandelwal** [comment]
Is this done? Should we close this?

**Comment by ramirezg** [comment]
Yep, it's done.

**Comment by rjmajma** [comment]
Got it. So we can anticipate most FOIA docs made public by the Federal gov are fairly manageable for our purposes?

**Comment by ramirezg** [comment]
These are mainly from fioaonline so we can't be 100% sure, but that seems to be the trend. Also, I think that pdfs converted from docs directly are smaller than pdfs that came from scans. The offices using foiaonline might use these types of documents more than others.
