### ISSUE TITLE
Minimal UI Wireframed Around the Search Prototype

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#497]
This includes: 
- [ ] Search home page
- [ ] Search results page
- [ ] Document viewing page

**Comment by vz3** [comment]
@vz3+@ericadeahl on this one

**Comment by ericadeahl** [comment]
@khandelwal please add screenshots of the prototype

**Comment by khandelwal** [comment]
![screen shot 2015-02-04 at 12 39 49 pm](https://cloud.githubusercontent.com/assets/636752/6194361/afc40a60-b391-11e4-80e7-c2920f98a3d8.png)

**Comment by khandelwal** [comment]
![screen shot 2015-02-04 at 12 39 38 pm](https://cloud.githubusercontent.com/assets/636752/6194366/b74bbb34-b391-11e4-932f-df951535dcc3.png)

**Comment by khandelwal** [comment]
![screen shot 2015-02-04 at 12 39 24 pm](https://cloud.githubusercontent.com/assets/636752/6194370/bbb98e08-b391-11e4-9690-b62000de22ce.png)

**Comment by khandelwal** [comment]
Sorry these are much later than you expected. But that's it!

**Comment by ericadeahl** [comment]
great thanks @khandelwal !

**Comment by khandelwal** [comment]
I used our existing CSS to make the Krang pages look a lot like the  current application (mostly I got tired of looking at the ugly HTML pages). Here are some screenshots:

![screen shot 2015-02-19 at 5 48 56 pm](https://cloud.githubusercontent.com/assets/636752/6277768/9935261c-b85f-11e4-8e84-819fe4900406.png)

**Comment by khandelwal** [comment]
![screen shot 2015-02-19 at 5 50 00 pm](https://cloud.githubusercontent.com/assets/636752/6277796/c00ae876-b85f-11e4-8633-46a00e7b1efa.png)

**Comment by khandelwal** [comment]
![screen shot 2015-02-19 at 5 50 26 pm](https://cloud.githubusercontent.com/assets/636752/6277798/ce9c67ca-b85f-11e4-8496-e23f5e50803a.png)

**Comment by khandelwal** [comment]
I don't know enough about CSS/HTML to know why that document viewer thing is so small (it should ideally be a bit bigger)

**Comment by ericadeahl** [comment]
victor's quick wireframes based on our group sketch session:

![home](https://cloud.githubusercontent.com/assets/5911280/6352262/396ca152-bbf6-11e4-8df9-0a4c475f0557.png)

![search results](https://cloud.githubusercontent.com/assets/5911280/6352268/3f3fb0c4-bbf6-11e4-8726-b2ac405a898a.png)

![desktop hd 3](https://cloud.githubusercontent.com/assets/5911280/6352276/441c2938-bbf6-11e4-82a9-a9d5842b62e4.png)

**Comment by ericadeahl** [comment]
More detailed UI for the search results:

![search results 2](https://cloud.githubusercontent.com/assets/5911280/6352300/6f8f4136-bbf6-11e4-9e9d-1d2696645eda.png)

completed search terms:

![search results 3](https://cloud.githubusercontent.com/assets/5911280/6352310/84eecc04-bbf6-11e4-940c-2a3ecc7623b4.png)

alternate table option (makes it easier to browse many documents quickly, but you must click to get the document description):

![search results 1](https://cloud.githubusercontent.com/assets/5911280/6352314/8a03ec56-bbf6-11e4-8764-38165b76fc53.png)
