### ISSUE TITLE
Understand Cloud Foundry and Staging Server

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#501]
In preparation for an eventual use of cloud foundry (or a similar paas) here are a few things we need to do:

- [x] Make a list of how the current FOIA-HUB application needs to change to be deployed on Cloud Foundry. 
- [x] Document the commands necessary to deploy an application to Cloud Foundry
- [x] Use this knowledge to setup a staging server for FOIA-HUB (non-krang version)
- [x] Get @ramirezg and @khandelwal set up to deploy

Time permitting:

- [ ] Look into auto deploys

**Comment by rjmajma** [comment]
Team FEC could take advantage of the work created as a result of boxes 1, 2, and documentation associated with 4. Please document well and share when complete.

**Comment by khandelwal** [comment]
SYNERGY

**Comment by khandelwal** [comment]
Are all the checkboxes done?

**Comment by ramirezg** [comment]
@khandelwal Actually looking back at this everything is documented here:
https://github.com/18F/foia-hub/blob/master/cloudfoundry.md

**Comment by konklone** [comment]
Yes, but we're not all the way onto Cloud Foundry yet.
