### ISSUE TITLE
Fix Copy on Agency Landing Pages

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#503]
We should adjust the copy, pictured here, to "Submit a request via the web", "Submit a request electronically" or "Submit a request via web form". 

![screen shot 2015-02-12 at 11 38 05 am](https://cloud.githubusercontent.com/assets/3649037/6171904/b2da67a8-b2ab-11e4-8a16-7b173da81750.png)

**Comment by ramirezg** [comment]
Changing this to help wanted. @rjmajma, do you mind specifying one of the options so somebody can help us out?

**Comment by khandelwal** [comment]
I wonder if it should display the URL for the site it's taking you to. That way you know you're leaving foia-hub before you click on that link. It's also analogous to "Request by email" and then providing the email address. 

We're a while away from providing a request form, so we can cross that bridge when we come to it.

**Comment by rjmajma** [comment]
Ooh. That's a great call, Shashank. I prefer that.

@vz3 and @ericadeahl, have any thoughts on this?

**Comment by ericadeahl** [comment]
+1 to displaying the URL

**Comment by rjmajma** [comment]
Would we then keep "Request Online" and replace "Submit a request via web" with the URL? Or is there a better way?

**Comment by ericadeahl** [comment]
Yes, that's what I was thinking. "Request Online" then URL below.

**Comment by rjmajma** [comment]
Yup. Let's make it so. Who would be the best person to complete this task?
