### ISSUE TITLE
Hold a collaborative sketching session with team, requester and Foia official

### ISSUE THREAD

**Issue by jtag** [18F/foia-hub#508]
What can we learn by (using known methods) collaborate on how search might best be surfaced to people searching proactive disclosures, responsive records, and "FOIA logs"

Two hour event  to discover mental models, IA, and search UI solutions beyond our understanding.

**Comment by jtag** [comment]
(Although I will be supporting this, assigning this to Victor to practice not being on FOIA stories)

**Comment by jtag** [comment]
Slated for Thursday 2/19

**Comment by jtag** [comment]
- [x] invite team
- [ ] invite and confirm FOIA requestor
- [ ] invite and confirm FOIA processor
- [ ] decide on technique for group sketching

**Comment by jtag** [comment]
@vz3 Can you reach out to the requestor you had in mind? I'll reach out to T/GSA.

**Comment by jtag** [comment]
FOLLOW UP TO DO:

- [ ] JT/ED share photos or scans of sketches in group folder in Design>Feb Sketching folder
- [ ] VZ share photos or scans of sketches in group folder in Design>Feb Sketching folder
- [ ] VZ post sketches on black foam core for whole team (and ambient DC peers) to see thinking externalized

**Comment by rjmajma** [comment]
Hey, can we close this @ericadeahl @vz3?

**Comment by ericadeahl** [comment]
Yes! Closing it.
