### ISSUE TITLE
Can we avoid using Typekit?

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#510]
I get the benefits of Typekit, but:

* The app now depends on a proprietary font, from a proprietary platform, that we're licensing on demand. This weakens the open source nature of the app (it's not enough for someone just to clone the code and run it) and adds a dependency we're not in complete control of.
* It reduces the privacy of our visitors: our app now pings Typekit's servers for every visit, sending details of the user's browser and other metadata to their service. Typekit's license structure doesn't allow us to copy and inline the font ourselves. If we used an open font, from Google Fonts or from [The League of Moveable Type](https://www.theleagueofmoveabletype.com/) or something similar, we'd be able to host it ourselves.

I'd like the team to at least explore other fonts which we like for the app, and can use in our app in a free (as in speech) and private manner.

cc @vz3

**Comment by rjmajma** [comment]
Moving this out of the sprint. Worth doing, just not something that should probably be added to the sprint.

**Comment by konklone** [comment]
Ah, sorry, should've left that for the team to judge.

**Comment by seanherron** [comment]
As long as you leave suitable non-proprietary fallbacks I see no issue with using Typekit (or typography.com, or any others). The reality is that a lot of open source fonts just aren't that nice or readable. If using a proprietary font means that the content is easier to understand, gives a more professional appearance, or enables greater use interaction, then we should use them. Ensuring that you fall back to something that still works means that individuals can still take the application and run it elsewhere, they just won't have the full, 100% look and feel that proprietary fonts give. I think that is a reasonable tradeoff.

To your second point on privacy, I know we've spoken about this before but I think the right step is to respect Do Not Track on our websites, either by ensuring third parties we work with respect it or by building it in to our applications on our own.

**Comment by konklone** [comment]
> The reality is that a lot of open source fonts just aren't that nice or readable.

I disagree, but in any case, I'd like the team to investigate open source fonts for our website before reaching that conclusion.

> Ensuring that you fall back to something that still works means that individuals can still take the application and run it elsewhere, they just won't have the full, 100% look and feel that proprietary fonts give. I think that is a reasonable tradeoff.

Depending on the site design, using a backup font can cause the layout to become distorted or text to wrap unexpectedly. Hopefully we're being careful about that, but that's extra design effort and I expect that we're not, and won't be in the long run. Designing for two fonts is work.

> To your second point on privacy, I know we've spoken about this before but I think the right step is to respect Do Not Track on our websites, either by ensuring third parties we work with respect it or by building it in to our applications on our own.

Typekit doesn't have any public indication of support for Do Not Track, even in the [blog post they refer people to about privacy](http://blog.typekit.com/2013/06/13/clarifying-our-commitment-to-privacy/). 

I don't understand what building in Do Not Track support for our own applications would do. If we can operate our websites without tracking users, then we should just do that all the time. Do Not Track is a weakly defined and sparsely implemented standard, aimed at services that have different business models and incentives than the federal government.

In any case, not linking to a third party site at all provides much better privacy protection than linking to a third party site that supports Do Not Track -- and TypeKit doesn't even appear to be one of those.

**Comment by seanherron** [comment]
> I disagree, but in any case, I'd like the team to investigate open source fonts for our website before reaching that conclusion.

Of course. I'm just going off my experience using a number of open webfonts and being pretty disappointed with the outcome. Ultimately that is probably a design decision that should be driven by the designer and usability research.

> Depending on the site design, using a backup font can cause the layout to become distorted or text to wrap unexpectedly. Hopefully we're being careful about that, but that's extra design effort and I expect that we're not, and won't be in the long run. Designing for two fonts is work.

I would say that is a cost that should be taken in to account when looking at the costs/benefits of using a proprietary font.

> I don't understand what building in Do Not Track support for our own applications would do. If we can operate our websites without tracking users, then we should just do that all the time. Do Not Track is a weakly defined and sparsely implemented standard, aimed at services that have different business models and incentives than the federal government.

By respecting DNT, we could not include third party items when we are unsure if they respect DNT or not. For this specific example, if it was determined that there was legitimate concern among users around Typekit, you could not include the Typekit code when a user's browser has DNT enabled. It's not an ideal solution, but it may be worth the cost if the design implications of not using a proprietary font are too high.

**Comment by jehlers** [comment]
The issue with open fonts is that they are less tested. You can usually tell that they are not as well made as many of the fonts you pay for. This can cause legibility issues. 

The other problem with many open fonts is that they don't always have all the characters you need. Many of them are made and then not kept up. They might not have characters for multiple languages or just not as many glyphs as you might need. 

That said, I could say some of the same things for a well made proprietary font vs a not poorly designed one. Which is why this is a decision that should be left up to the designer. There are many constraints when choosing a font both brand and otherwise. I think it would be great to use open fonts where we can, but I don't think it is something that should be dictated from the beginning. There is a lot that goes into the choice of a font and font family that goes beyond whether it is open or not.

**Comment by konklone** [comment]
> I think it would be great to use open fonts where we can, but I don't think it is something that should be dictated from the beginning. There is a lot that goes into the choice of a font and font family that goes beyond whether it is open or not.

I completely agree, and my issue title is sincerely put in question form. I would like the tradeoffs to be something we weigh -- I know it's not always thought of that way, and that at prior jobs both I and my design colleagues freely used Typekit without weighing these tradeoffs.

**Comment by vz3** [comment]
The plan has been to purchase the typeface (Proxima) before public launch and hosting it on our servers. As @jehlers pointed out, readability (i.e. usability) is the most important priority from our perspective, and that makes most of the Google Fonts at least a non-starter.

That said, [League of Movable Type](https://www.theleagueofmoveabletype.com/) looks promising and worth looking into more.

**Comment by khandelwal** [comment]
We're not tracking the need to purchase proxima anywhere. Should we be?

**Comment by rjmajma** [comment]
Seconded. @vz3, whatever needs to be purchased should be figured out soon.

**Comment by khandelwal** [comment]
We are going to be purchasing Proxima and it will be self-hosted.

**Comment by khandelwal** [comment]
- [ ] Buy the font
- [ ] Host the font

**Comment by rjmajma** [comment]
Created a new issue #562 for Shashank's last comment.
