### ISSUE TITLE
Rework data loading to not depend on the disk

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#511]
Our approach to data loading won't work on a Heroku or Cloud Floundry environment, where the disk is ephemeral and non-guaranteed.

Some options:

* Use GitHub Pages, or the GitHub Repo Contents API, to fetch the YAML files on demand over HTTPS and load each one directly into memory.
* Publish the data files to S3, possibly automated or possibly by hand, and download them on demand from there over HTTPS.
* Move them into the foia-hub repo itself (eesh).
* Have the data loading process taken care of in a totally separate part of Cloud Foundry that _does_ have a guaranteed disk, at least for a period of time. Possibly the [one time task](https://blog.starkandwayne.com/2014/07/14/running-one-time-tasks-in-cloud-foundry/) infrastructure does this -- I'm not sure.

cc @dlapiduz re: #501

**Comment by dlapiduz** [comment]
@konklone for this kind of stuff I usually use CI to build the site and push it to CF. That way you guarantee that the content is immutable and you don't have to do any weird hacks.

Would that work for you?

**Comment by konklone** [comment]
@dlapiduz This is a bit different. This repo, foia-hub, depends on a [different repo](https://github.com/18F/foia) that has [a set of managed, versioned data files](https://github.com/18F/foia/tree/master/contacts/data). This app, foia-hub, has a data loading task that is given a reference to a location on disk where those data files are. This doesn't work in a Heroku environment, and I expect it won't work in a CF environment. We could adapt the data loading script to auto-clone the repo locally as needed, but I'm not sure how local disk is managed for Cloud Foundry projects.

**Comment by cmc333333** [comment]
@dlapiduz are you saying that none of the loading should happen on cloud foundry? I read your comment as "load the db during CI, when you have full shell access"; is that accurate?

**Comment by konklone** [comment]
@dlapiduz and I talked over video, and he was advocating having CI take the data files and sync them up to S3. Then, the data loading process would look to S3 and make individual requests for each file. This would entail us adding some logic to handle possible failures/retries.

For my part, I'd still like to get through this without additional infrastructure. I'm going to rewrite the data loading task to do the `git clone, and try to do that within Cloud Foundry.

But in any case, we will need to think about how to automate data loading in a PaaS -- a scheduled task of some kind.
