### ISSUE TITLE
Add social information for each agency in info box

### ISSUE THREAD

**Issue by melodykramer** [18F/foia-hub#513]
Just a suggestion for later down the road.

There's a social media API that lists all of the social handles for each gov't agency: http://www.usa.gov/About/developer-resources/social-media-registry.shtml

Might be useful for users to be able to contact the agencies that way too -- or even just to have the information so they know it exists.

**Comment by khandelwal** [comment]
Will FOIA requestors use this as a way to contact an agency? The social media strategist at the agency and the FOIA processors are likely not the same people, so it's unlikely any customer service would be offered in this case. 

The social handles for each agency *are* useful, but remember that we're providing a FOIA specific address book. Any other piece of information would create noise.

**Comment by melodykramer** [comment]
Ooh. Good point.

**Comment by ramirezg** [comment]
@melodykramer working with Social Media Registry seems like a really cool project, even if it might not be important for FOIA. It could be an endless source of Data Science blog posts. We should talk about it sometime.
