### ISSUE TITLE
Do we need a better 'no results' page?

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#520]
Here's what our current "no results" page looks like. 

![screen shot 2015-02-18 at 4 39 23 pm](https://cloud.githubusercontent.com/assets/636752/6257258/ba2aef74-b78c-11e4-91f5-0a9b00bd4fb2.png)

you can see the page here: https://foia.18f.us/agencies/?query=shashank

I'm thinking we probably need a better looking/more useful page? This to me looks like a placeholder.

**Comment by ericadeahl** [comment]
Null search results page styling (matches styling from search results.) It would be nice to add suggestions of things people can search for, but I don't think we need to prioritize that for this sprint - let's just hit styling for now.

![foia_nullsearchresults](https://cloud.githubusercontent.com/assets/5911280/6453259/005a79d4-c0f1-11e4-98bd-d05b48639bca.png)

**Comment by rjmajma** [comment]
Implementing will be a separate ticket.

**Comment by vz3** [comment]
I'd like to see some more copy here. How can we help users get to where they're trying to go?

Perhaps below the above, we can put some copy along these lines:
`There are no results for your search. You can try searching again with a different query, or you can [browse our list of all federal agencies](#)."

**Comment by rjmajma** [comment]
Here's what we did for FEC @vz3 and @ericadeahl. https://github.com/18F/openFEC/issues/306

**Comment by ericadeahl** [comment]
@vz3 i like your suggestion. Linking to the federal agencies page is simple but good.

I also like how FEC has that "still no luck? we're in beta, try fec.gov" disclaimer - but there's not really another place we can send people. Perhaps we could have a line that says something like "Still no luck? This site is in alpha. Help us improve by telling us what you're looking for" + link to About This Project

**Comment by rjmajma** [comment]
That's a good point and a great suggestion, @ericadeahl. +1
