### ISSUE TITLE
Contacts Update Form

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#526]
We need something similar to foia.gov's annual report generator: 
http://www.foia.gov/xmlgen/
for the contacts information.

This will have the following features: 

- [x] Each Agency has one form, with some way to enter in information for the various components. 
- [x] Form submission generates a JSON file with the information that agencies are instructed to put in the *same* location as their quarterly report zip file. 
- [x] Form should pre-populate from the latest data from the API 
- [x] The generated file should have a timestamp in the name, so that we know if we've picked that file up. 
- [x] Lives in foia-hub

**Comment by khandelwal** [comment]
We should probably add messaging that indicates that agencies can put the file on their servers at any time (as long as it's in the same place as where the quarterly reports go). So that we can get updated information whenever it's possible.

**Comment by khandelwal** [comment]
Something like the contenteditable tag might be useful to use: http://caniuse.com/#feat=contenteditable

**Comment by cmc333333** [comment]
<3 contenteditable

**Comment by ramirezg** [comment]
I'm working on an [mvp here](https://github.com/18F/foia_contacts/pull/1). Still needs a lot of work but it's a start. 
Any good example of how to hook up contenteditable to form? Or use Django forms with a variable number of fields?

**Comment by khandelwal** [comment]
I think @cmc333333 has some sample contenteditable code somewhere. @cmc333333 is the eregs editor stuff available somewhere @ramirezg can have a look at?

**Comment by khandelwal** [comment]
Also maybe look at Django formsets?

**Comment by ramirezg** [comment]
@cmc333333 do you know if you can use contenteditables in forms without javascript?

**Comment by ramirezg** [comment]
Do we want this functionality? 
________
![screen shot 2015-02-23 at 5 16 06 pm](https://cloud.githubusercontent.com/assets/4596845/6338830/b0837788-bb7f-11e4-9d29-cee826753c35.png)

**Comment by khandelwal** [comment]
No, because we'd always populate it with the latest data we have.

**Comment by cmc333333** [comment]
@ramirezg - I think you could turn it on (just add the contenteditabe=true attribute), but then you'd never be notified when changes are made. You could try making a form and giving a div a "name" attribute, but I don't think that'd work.

The way I understand it, you add event listeners on `blur` and `focus` events for when the user exists/enters the block of content. Does that make sense?

**Comment by ramirezg** [comment]
@cmc333333 sort of. Do you mean change css to make the inputs look like contenteditabe. ie set `input:focus` for the forms etc. ?

I think the whole point of using contenteditabe was to make the form look a little nicer, but it seems that there isn't really a good way make contenteditabes work with django form validations.

**Comment by cmc333333** [comment]
@ramirezg : no I mean listening for JS events. E.g. w/ jquery:
```javascript
$('#my-element').blur(function() {
    alert("You wrote " + $(this).html());
});
```

Keep in mind that django form validation doesn't require an HTML form -- you could pass everything as JSON over AJAX, for example. You could also use JS to set values on a traditional HTML form and submit that, if that's your fancy. IIRC, Sir Trevor's django instance waits until you click submit, at which point it fires an event to crawl over the editable html and store that as hidden elements in the form.

Does that help?
