### ISSUE TITLE
Add analytics to document search

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#528]
- [ ] Figure out what questions we want our analytics to answer 
- [ ] Implement analytics to answer those questions

At the least I'm imagining we'll need to know what terms users used to search, how many search results they got back, and whether they clicked on (and maybe even downloaded) a result.

It would also be useful to know if they specifically clicked on one of the 'more like this' results as well.

**Comment by vz3** [comment]
Questions: 
Are users scrolling on the home page?
Are users who are using the search tool ending up at an agency landing page? Do they spend enough time on that page that indicates that they are taking an action?
What are users entering into the search box? How does the search traffic compare between homepage and small search?

**Comment by ramirezg** [comment]
We now have basic event tracking on analytics.
