### ISSUE TITLE
Build API endpoint to quickly populate contact form

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#536]
The [FOIA Contact Updater app](https://github.com/18F/foia_contacts) uses the contacts API to populate its form. Unfortunately, since the design requires us populate contact information for both agencies and their offices on one page, the updater has to hit both Agency and Office endpoints. Hence, populating agencies like the DoD takes a while. 

Ideally we would have an endpoint with the specific fields we would like to collect from agencies.

**Comment by ramirezg** [comment]
I actually think we don't need this. Using the api resources directly make the updates quick. These pages also won't be highly trafficked.

**Comment by rjmajma** [comment]
Do you agree, @khandelwal?

**Comment by khandelwal** [comment]
Yeah, I think that's fine.
