### ISSUE TITLE
QA Check

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#538]
I wanted to expand on the work done in #445 and take a look at the site as a whole. PR #537 fixes the things I could identify and work on. The following require fixes I can't implement. 

Found a bug in the first reading room link for BSEE. Currently takes you to https://foia.18f.us/About-BSEE/FOIA/BSEE-FOIA-Reading-Room/. 

![screen shot 2015-02-24 at 12 54 19 am](https://cloud.githubusercontent.com/assets/3649037/6343983/c03d2634-bbbf-11e4-94a0-5a159ed789de.png)

**Comment by rjmajma** [comment]
Additional bug found with CFTC. First link takes you to https://foia.18f.us/FOI/foiareadingrooms. 

![screen shot 2015-02-24 at 12 58 25 am](https://cloud.githubusercontent.com/assets/3649037/6344029/45618710-bbc0-11e4-815a-44898754ae01.png)

**Comment by rjmajma** [comment]
CEQ reading room links take you to the same location (not distinguished from proactive disclosure versus foia disclosure). http://www.whitehouse.gov/administration/eop/ceq/foia/readingroom

![screen shot 2015-02-24 at 1 00 54 am](https://cloud.githubusercontent.com/assets/3649037/6344044/9ce9330c-bbc0-11e4-9fd0-2ca8e4731b85.png)

**Comment by rjmajma** [comment]
Same issue from above with DNFS. Also an error with the display of the first link. http://www.dnfsb.gov/foia-reading-room

![screen shot 2015-02-24 at 1 02 14 am](https://cloud.githubusercontent.com/assets/3649037/6344055/cb019d38-bbc0-11e4-942f-7fd4d64831a5.png)

**Comment by rjmajma** [comment]
EPA's reading rooms are a bit of a mess. Some regional offices have a few broken links. Consolidating this per #539 may help. Either way, they should not link to http://www2.epa.gov/foia. They should link to FOIA Online, as that's where the library is.

**Comment by rjmajma** [comment]
EXIM links to the wrong website location. This is where it should go: http://www.exim.gov/about/library/foia/

![screen shot 2015-02-24 at 1 10 47 am](https://cloud.githubusercontent.com/assets/3649037/6344124/fb521aca-bbc1-11e4-8039-b192e1220f93.png)

**Comment by rjmajma** [comment]
FSCIC also repeats. 

![screen shot 2015-02-24 at 1 15 33 am](https://cloud.githubusercontent.com/assets/3649037/6344156/adbb4fb0-bbc2-11e4-82f7-303c8a1d6ca7.png)

**Comment by rjmajma** [comment]
FEMA's FOIA page is broken. It's listed correctly, just doesn't work. Thoughts?

Also, the request page is incorrect. It should send here: https://www.fema.gov/submit-foia-request-nac-information

![screen shot 2015-02-24 at 1 18 46 am](https://cloud.githubusercontent.com/assets/3649037/6344178/1cb13aba-bbc3-11e4-96ea-f92669886cc7.png)

**Comment by rjmajma** [comment]
FERC's submit link is incorrect. I believe it should send here: http://www.ferc.gov/legal/ceii-foia/foia/foia-new-form/FOIARequest.aspx

![screen shot 2015-02-24 at 1 19 46 am](https://cloud.githubusercontent.com/assets/3649037/6344189/3c604ca2-bbc3-11e4-8230-cf5309b7312d.png)

**Comment by rjmajma** [comment]
FLETC library has two links (both of which are broken. Not our mistake). 

![screen shot 2015-02-24 at 1 23 41 am](https://cloud.githubusercontent.com/assets/3649037/6344242/cc26cece-bbc3-11e4-936a-ef2730d363ce.png)

**Comment by rjmajma** [comment]
FOMC "Reading Rooms" link should be removed. Each link takes you to the same page. What's most useful is to keep the other two links because they at least take you to their respective spots on the same FOMC page.

![screen shot 2015-02-24 at 1 26 38 am](https://cloud.githubusercontent.com/assets/3649037/6344282/34646be0-bbc4-11e4-949d-544b0a94461a.png)

**Comment by rjmajma** [comment]
FTC reading room has duplicates. Remove the last link. 

![screen shot 2015-02-24 at 1 27 41 am](https://cloud.githubusercontent.com/assets/3649037/6344295/58559e98-bbc4-11e4-96ef-4a2ca7b39d45.png)

**Comment by rjmajma** [comment]
FLRA Dallas and Denver regional offices have the same email address. Not sure if this is correct. Can you do a quick spot check @ramirezg?

**Comment by rjmajma** [comment]
JPL site link should be fixed to send the user here: http://www.fmcs.gov/internet/itemDetailNoNav.asp?categoryID=90&itemID=16303

![screen shot 2015-02-24 at 1 31 54 am](https://cloud.githubusercontent.com/assets/3649037/6344319/eeb8ef66-bbc4-11e4-8bf6-ee676582eee6.png)

**Comment by rjmajma** [comment]
Marine Corps reading room links are labeled differently but take you to the same place. 

![screen shot 2015-02-24 at 1 33 24 am](https://cloud.githubusercontent.com/assets/3649037/6344335/25f4f556-bbc5-11e4-8885-c64aa8bbd080.png)

**Comment by rjmajma** [comment]
NTSB FOIA library link is incorrect. It ends with .html but should be: http://www.ntsb.gov/about/foia/Pages/foia_err.aspx. 

The main site link has a similar problem and should go here: http://www.ntsb.gov/about/foia/Pages/default.aspx

![screen shot 2015-02-24 at 1 47 48 am](https://cloud.githubusercontent.com/assets/3649037/6344494/2be4ca98-bbc7-11e4-80ae-2996b67a2964.png)

**Comment by rjmajma** [comment]
NSA email duplicated for some reason. One should be removed. 

![screen shot 2015-02-24 at 1 48 50 am](https://cloud.githubusercontent.com/assets/3649037/6344503/5324a376-bbc7-11e4-8e48-44f35a8be03b.png)

**Comment by rjmajma** [comment]
NRO email is duplicated as well. One should be removed. 

![screen shot 2015-02-24 at 1 49 28 am](https://cloud.githubusercontent.com/assets/3649037/6344505/695987ba-bbc7-11e4-9c55-44045e7ce9a7.png)

**Comment by rjmajma** [comment]
NHTSA request online link should be removed. The agency has no web form (that I have found) and it only provides information on how to email/write the agency.

![screen shot 2015-02-24 at 1 52 41 am](https://cloud.githubusercontent.com/assets/3649037/6344532/d5e2868e-bbc7-11e4-8895-1a3b85602cfc.png)

**Comment by rjmajma** [comment]
NARA has a few weird points. The true regional offices do not have reading room links. We should consider adding them. 

Another issue is that Accessioned Executive Branch Agency Records - Washington, DC Area, Main Office, and OIG both have two reading room links that take you to the same place. One should be removed. 

![screen shot 2015-02-24 at 1 56 52 am](https://cloud.githubusercontent.com/assets/3649037/6344574/6c29c45e-bbc8-11e4-9931-970425272d6d.png)

**Comment by ramirezg** [comment]
@rjmajma Nice catch noticing that the FLRA Dallas and Denver regional offices have the same email. This is actually an error on foia.gov, which we can fix in the manual data.

**Comment by ramirezg** [comment]
> JPL site link should be fixed to send the user here: http://www.fmcs.gov/internet/itemDetailNoNav.asp?categoryID=90&itemID=16303

wait, why should JPL link to FMCS?

**Comment by ramirezg** [comment]
> NSA email duplicated for some reason. One should be removed.

@rjmajma I'll look into this.

**Comment by ramirezg** [comment]
> NHTSA request online link should be removed. The agency has no web form (that I have found) and it only provides information on how to email/write the agency.

@rjmajma I think the form pops up when you click `here` it's just not very descriptive though. 

![screen shot 2015-02-24 at 10 53 24 am](https://cloud.githubusercontent.com/assets/4596845/6352825/61469d46-bc13-11e4-9ae7-9aabc64ad357.png)

**Comment by rjmajma** [comment]
Hey @ramirezg: 

Wrong link to JPL. It should be this: http://www.hq.nasa.gov/office/pao/FOIA/jpl/index.htm. I'll fix in the comment as well. 

That's a shame about NHTSA. Keep it.

**Comment by ramirezg** [comment]
@khandelwal I see that you're assigned to this issues, but I have some time today so I can take care of the following:
- [ ] fix the emails for the FLRA Dallas and Denver regional offices
- [ ] update the FERC's submission link
- [ ] remove duplicate emails
- [ ] fix the JLP office url

**Comment by khandelwal** [comment]
Figure out how the duplicate emails get in there, and ensure that the software doesn't let that happen again. I'm guessing we don't check to see if it's already in there somewhere.

**Comment by ramirezg** [comment]
Ok, took care of the issues here 18F/foia/pull/104 and found the source of the email dups. I'm updating the contacts now.

**Comment by khandelwal** [comment]
A lot of the issues reported in here should now be fixed. Let's check them (and then close this issue).
