### ISSUE TITLE
Discuss #497 as a team

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#542]
Determine what we are able to actually do in the wireframes. 

#497

**Comment by rjmajma** [comment]
Creates a dependency for #559.

**Comment by rjmajma** [comment]
We discussed this Friday afternoon. It was super productive. We decided to: 
- Create a set of wireframes that would cover documents that do not contain a substantive amount of associated metadata. This would be require us to adjust the most recent wireframes from #497. 

Is this correct, @ericadeahl?

**Comment by ericadeahl** [comment]
@rjmajma Yes! We will adjust the wireframe/design to accommodate both documents that do not have title/date/metadata and documents that do. I'll post updated work in #559.

There was also an unresolved question from @khandelwal about our strategy for obtaining new documents and how it would affect the questions we want answered in testing. We discussed two options - to focus on collecting documents from particular agencies/components, or to collect documents around a particular topic from multiple agencies. Should we open a new issue around document intake?

**Comment by rjmajma** [comment]
I think intake strategy will be an ongoing issue. I'll leave it to @khandelwal on whether we make it its own separate issue or just continue working on it as we have been.

That being said, I think the goal of this sprint has been closed out.
