### ISSUE TITLE
Implement new wordmark

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#544]
New wordmark is available in #401. Should implement the new wordmark on the current site.

**Comment by ericadeahl** [comment]
Also need to update all mentions of "FOIA Hub" to "openFOIA"

**Comment by rjmajma** [comment]
Yup. That's coming in a content PR soon.

**Comment by vz3** [comment]
Playing around with a couple hover/focus state options. Feedback welcome! cc @ericadeahl 

# Default state
![logo1](https://cloud.githubusercontent.com/assets/582918/6540030/d9e811e4-c456-11e4-8183-0d58248d6f03.png)

# Hover 1
![logo2](https://cloud.githubusercontent.com/assets/582918/6540031/ddb4431a-c456-11e4-84d2-c0297d0bb133.png)

# Hover 2
![logo3](https://cloud.githubusercontent.com/assets/582918/6540033/e1deb59c-c456-11e4-91fd-9c7716f5943a.png)
