### ISSUE TITLE
Duplicate elements

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#545]
For example, NASA Shared Services Center (NSSC) 
[Migration 0018](https://github.com/18F/foia-hub/blob/master/foia_hub/migrations/0018_delete_office_dups.py) should take care of this issue. We might need to run it again on the server. 

![test](https://cloud.githubusercontent.com/assets/4596845/6358419/5a72593a-bc39-11e4-95b3-aa594ef0b4b8.png)

**Comment by khandelwal** [comment]
If we wipe the database clean and reload the data, does that fix it?
