### ISSUE TITLE
Load Agency Contacts Function Update

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#550]
`load_agency_contacts.py` needs to have a `delete_unused_contacts` function to get ride of duplicates created when the data shift around.

**Comment by khandelwal** [comment]
I'm not sure that's quite right. I think we should ensure duplicates never enter the dataset. Not clean them up afterwards. 

(I know we might have to clean them up once).

**Comment by ramirezg** [comment]
You're right, but I'm referring to another issue. Sometimes elements like NASA Shared Services Center (18F/foia-hub/issues/545 ) enter the database one way and then another way after we clean up the yaml files. Currently migration 0018 takes care of these instances, but we can't keep running it again when we are in production.

**Comment by khandelwal** [comment]
There's no reason to keep updating the database. When we get a new dataset, we should just wipe the database clean and start again. It's a reproducible dataset and there's no reason to add fancy logic.

**Comment by ramirezg** [comment]
@khandelwal so I was thinking about this yesterday. Resetting the database might be okay for now, but what about when the Agency and Office models are connected to the document models?

**Comment by khandelwal** [comment]
Ok, let's open this for discussion.

**Comment by ramirezg** [comment]
One possible solution for deleting agency contacts. 18F/foia-hub/pull/565

I'm thinking if we want to clear the data we could drop all the elements except the scaffolding elements like `slug`, `name`, `parent`, `parent_id`, `id`, that way any foreign keys connecting to these elements won't be broken.
