### ISSUE TITLE
Create an RDS instance within the CF VPC

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#551]
We'll use RDS for Postgres. We'll need to create an RDS instance inside the **Cloud Foundry VPC**, and provide the connection string to the app.

**Comment by khandelwal** [comment]
Depends on #552

**Comment by cmc333333** [comment]
Doesn't cloud foundry have a resource/module/whatever that does this for you? @dlapiduz

**Comment by dlapiduz** [comment]
@cmc333333 there is a system to do this kind of stuff, we haven't built an adapter for RDS yet

**Comment by khandelwal** [comment]
Per #552 this is done for staging. Once everything is hooked up and working we can do a production instance.

**Comment by dlapiduz** [comment]
@cmc333333 there is a "services" concept but we haven't built the service to spin up RDS instances yet.
