### ISSUE TITLE
Create ELB for FOIA in the CF VPC

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#553]
We'll terminate HTTPS on an ELB that forward (over HTTP) to the Cloud Foundry router, inside the same VPC. We need to create that ELB ourselves, and configure its ports.

**Comment by konklone** [comment]
A note that @dlapiduz and I made tons of progress on this today. 

* @dlapiduz [made a CloudFormation template](https://github.com/18F/cloud-foundry-manifests/blob/master/provisioning/elb.json) that creates the ELB, and associated Route53 record for the selected hosted zone.
* I [updated 18F's ELB TLS ciphers](https://github.com/18F/tls-standards/pull/34) to remove RC4 in accordance with current best practices, and these were reflected in @dlapiduz' CloudFormation template.
* I opened [a near-finished pull request](https://github.com/18F/cloud-foundry-notes/blob/elb/operation-and-deployment/elb.md) documenting that CloudFormation template and the steps it implies that I'm looking for DevOps to fill in the gaps on.

When that last one is done, I can deploy the ELB via CloudFormation and we should be in business. We're tracking the necessary work in the DevOps Guild Trello.

**Comment by khandelwal** [comment]
We would need a filled in CloudFormation template with all our settings right? Let's make sure we have that somewhere.

**Comment by konklone** [comment]
@dlapiduz made an [example filled-in shell script](https://github.com/18F/DevOps/blob/master/cf/create-elb.sh) for a test `*.18f.us` site, that uses the template JSON and fills in the parameters with the Cloud Foundry subnet IDs, etc.

I personally don't think the values in there are sensitive, but it's DevOps' call. So I think that as long as [my open PR](https://github.com/18F/cloud-foundry-notes/pull/8) is completed, we create a `foia.sh` file in the DevOps repo and link to it from our README somewhere, and then we actually deploy an ELB in the CF VPC using it, we can close this ticket.

**Comment by konklone** [comment]
@dlapiduz We need a change to the CloudFormation template. [These lines](https://github.com/18F/cloud-foundry-manifests/blob/master/provisioning/elb.json#L149-L153) require that we're using a subdomain within a parent hosted zone, e.g. `test.18f.us` inside of an `18f.us` hosted zone:

```
"Name" : { "Fn::Join" : [".", [
    { "Ref" : "ZoneName" },
    { "Ref" : "HostedZoneName" } ]
  ]
}
```

However, we are going to be using the apex of our hosted zone. In the case of e.g. `open.foia.gov`, we want to set an `A` record for `open.foia.gov` itself that is an `ALIAS` to the ELB. It looks like if I were to set a `ZoneName` of `""` that it would then create a `Name` field of `.open.foia.gov`. Maybe that will work right? But I'd rather fix it to just use the name we give it.

**Comment by konklone** [comment]
Also, I finished and merged in the PR about ELB creation, so the [documentation is here](https://github.com/18F/cloud-foundry-notes/blob/master/operation-and-deployment/elb.md).

I've created [`foia.sh`](https://github.com/18F/DevOps/blob/master/cf/foia.sh) in our DevOps repo, to wield that [Cloud Formation template](https://github.com/18F/cloud-foundry-manifests/blob/master/provisioning/elb.json) with the private subnet/security-group info and client tag name, etc. However, it's using the `*.18f.us` cert for now, which will be invalid, and I need resolution on the `Name` issue I raised in my previous comment.

**Comment by dlapiduz** [comment]
@konklone please feel free to change the template as you see fit. We don't need to use the exact same template every time. This is more like an example (at least for now).

Eventually we can add more logic to the template to add this use case.

**Comment by konklone** [comment]
I've created the ELB `CF-ELB-Test-ELB-19990PVNRCPL0`, using [`foia.sh`](https://github.com/18F/DevOps/blob/master/cf/foia.sh)

* https://github.com/18F/DevOps/commit/b6f719e162a6f0ad2940ad434e90778be12dbd05 - specifying the proper cert name, removing `ZoneName`
* https://github.com/18F/cloud-foundry-manifests/commit/2b6f83d3579d97319c372281a16eed70693d6043 - removing `ZoneName` from elb.json

@dlapiduz, I believe you have to update Cloud Foundry to allow that ELB to talk to the CF router?

@rjmajma and team - the plan here is to make `https://open.foia.gov` work publicly for just long enough to validate that everything works. After this is verified, I'll delete the A record and preserve its value in this ticket for manual reinstatement upon launch. Between then and launch, the team can use `/etc/hosts` to pretend that the A record exists and privately access the site through https://open.foia.gov. To launch to the public, you'll only need to restore the A record. 

Future re-deployments of new ELBs won't need manual DNS work, but right now we continue to have a manual step of 18F DevOps telling CF about the new ELB.

I'll leave this ticket open until the above happens -- assigning to @dlapiduz to tell CF about the new ELB.

**Comment by dlapiduz** [comment]
@konklone it is in there and looking good!

**Comment by konklone** [comment]
This is done and works perfectly! Thanks, @dlapiduz.

**Comment by konklone** [comment]
The DNS record was an `A` record that used R53's `ALIAS` option to point the record to `dualstack.cf-elb-test-elb-19990pvnrcpl0-1133059661.us-east-1.elb.amazonaws.com.`.

The record has been removed. It can be restored to make the site publicly accessible.

This (for now anyway) evaluates to an `A` record to `54.85.150.222`, so you can set that IP to `open.foia.gov` in your `/etc/hosts` file to access the production site.

**Comment by konklone** [comment]
Note that Amazon does in fact change the underlying IP addresses from time to time. I just had to change mine to `54.152.166.225`.

To get the latest IP that you can put in `/etc/hosts`, run this command and grab any of the resulting IPs:

```
$ nslookup dualstack.cf-elb-test-elb-19990pvnrcpl0-1133059661.east-1.elb.amazonaws.com

Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	dualstack.cf-elb-test-elb-19990pvnrcpl0-1133059661.us-east-1.elb.amazonaws.com
Address: 54.152.166.225
Name:	dualstack.cf-elb-test-elb-19990pvnrcpl0-1133059661.us-east-1.elb.amazonaws.com
Address: 54.165.114.167
```
