### ISSUE TITLE
Set up error monitoring

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#556]
This can be done in one of two ways:

* New Relic application monitoring - we add a New Relic Python or Django module to our application, and use it to report 404/500/custom/etc to New Relic.
* "Traditional" or other error monitoring - straight emails, or another services besides New Relic.

cc @afeld, who is working on New Relic stuff (Aidan, I'm syncing the FOIA-owned tasks to our team's issue tracker, for the team's visibility and participation.)

**Comment by afeld** [comment]
Per [a DevOps discussion](https://github.com/18F/DevOps/issues/160#issuecomment-75817891), we should now be able to monitor as many applications in New Relic as we need. Happy to try following [the setup instructions](https://docs.newrelic.com/docs/agents/python-agent/getting-started/new-relic-python) myself in the next few days if y'all are busy w/ other stuff, or feel free to give it a shot.

**Comment by afeld** [comment]
...especially if you have more experience w/ FOIA/Python than I do.

**Comment by khandelwal** [comment]
@ramirezg will work with @afeld

**Comment by afeld** [comment]
* [ ] Create a FOIA subaccount in New Relic – @dlapiduz

**Comment by afeld** [comment]
@dlapiduz created the account in New Relic – DM me on Slack if you don't have access but want it.

**Comment by khandelwal** [comment]
Looks like the list isn't done.

**Comment by ramirezg** [comment]
@afeld so I started New Relic on the server. It says it's running, but no data appears to be getting through.  (https://rpm.newrelic.com/accounts/909294/applications/5181761)

**Comment by konklone** [comment]
New Relic shouldn't need to be running as a daemon on the server - we're only using application monitoring, not server monitoring, right?

**Comment by afeld** [comment]
> we're only using application monitoring, not server monitoring, right?

New Relic monitoring on Cloud Foundry won't be as relevant, so that seems like a good plan to me.

> It says it's running, but no data appears to be getting through

Weird. Getting any warning as the application restarts? Feel free to catch me on Slack and we can debug.

**Comment by ramirezg** [comment]
@konklone @afeld : The issue is the high security settings 

```
CRITICAL - Disconnection of the agent has been requested by the data collector for the application 
where the agent run was None. The reason given for the forced disconnection is "Account Security 
Violation: The agent's local 'high_security' setting is true but this account is not configured for high 
security. It can be set at https://rpm.newrelic.com/accounts/909294/high_security". Please contact New 
Relic support for further information.
```

But it seems that `Only the account owner can enable enterprise security mode.`

**Comment by konklone** [comment]
Yep, that looks right. I'm in support of turning that on. I'll raise it with DevOps.

![screenshot from 2015-03-02 15 05 10](https://cloud.githubusercontent.com/assets/4592/6449255/8abd0f78-c0ed-11e4-829f-05be62f1cd7f.png)

**Comment by konklone** [comment]
@ramirezg @afeld I'm told that high security mode is now enabled for the FOIA subaccount on New Relic. Give it a go?

**Comment by ramirezg** [comment]
@konklone @afeld looks like it's up and running with high security. I think we just need to incorporate it into the fab script now. 
![screen shot 2015-03-02 at 5 35 18 pm](https://cloud.githubusercontent.com/assets/4596845/6452266/8b75a58c-c102-11e4-892a-75d04252f1b2.png)

**Comment by konklone** [comment]
Sorry, I still don't understand why we need to incorporate anything into the fab script, or why anything needs to be running on the server. We're only doing application monitoring, not server monitoring. So, any errors can be reported in-process by using a Python library that talks directly to the New Relic servers.

In any case, our use of `fabric` is coming to a close pretty soon. We should limit our deployment work to supporting our Cloud Foundry use case.

**Comment by ramirezg** [comment]
@konklone sorry, I should have been clearer. I just wanted to make sure that the `NEW_RELIC_LICENSE_KEY` was in the `foia-env` file so it gets picked up when we deploy.

**Comment by konklone** [comment]
Ahhh yes, totally. Thanks for clarifying.

**Comment by khandelwal** [comment]
Where are we with this?

**Comment by khandelwal** [comment]
We have new relic setup, but we don't have it setup in cloud foundry. We need to set an environment variable.
