### ISSUE TITLE
First pass at design of Search, Search Results, Document Viewing

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#559]

**Comment by ericadeahl** [comment]
@rjmajma @khandelwal @vz3 @ramirezg Here's a pass at Search Results and Document Viewing page. Thoughts?

**Search Results**
- You can do full text search, filter by agency, and filter by PDF/CSV
- Sorting is by Relevance or Date Released
- Displays 3 text excerpts with search terms separated by ellipses...
- Displays whatever metadata is available: Agency, format, date created, date released
- If document has no title, displays [no title] - anyone have other ideas here??

![search results](https://cloud.githubusercontent.com/assets/5911280/6497137/8528e1dc-c290-11e4-952a-710751125622.png)

- my thought was that users could add multiple agencies to filter by and they would appear as tags

![search results 2](https://cloud.githubusercontent.com/assets/5911280/6497404/0da72606-c294-11e4-810e-f98a38f6899a.png)

- maybe a simpler way to do it would be to have a dropdown filter that shows how many results correspond with a particular agency

![agency filter 2](https://cloud.githubusercontent.com/assets/5911280/6497407/13402e6e-c294-11e4-97d2-21b36eeb6401.png)

**Document Viewing Page**
- outstanding question - what do we do with a csv?

![document page](https://cloud.githubusercontent.com/assets/5911280/6497139/89cefc12-c290-11e4-8a1c-83cb29741f5a.png)

**PDF Viewer**
- the document page would have a preview of the first page; clicking on it would open a pdf viewer similar to gmail

![pdf viewer](https://cloud.githubusercontent.com/assets/5911280/6497142/8fc3427c-c290-11e4-9e50-a7f7cf9f2a91.png)

**Comment by khandelwal** [comment]
A few random thoughts: 

A. I'd push back on being able to filter by PDF or CSV. One: CSV isn't that common of a format for an agency document release (we're more likely to see XLS). Two: I don't think the document format conveys any meaning (it's unlikely agencies are logical about the format they pick). Let the algorithms decide what floats up to the top. 

B. Instead of [no title] how about simply displaying the file name? That way there's at least something there. 

C. Let's figure out CSVs far down the line. I'm not sure we lose anything by maybe only focusing on PDFs at this point. 

D. I was thinking it might be nice for the related documents  section to be a bit more concise. 

E. PDF viewer: the first page of a government document isn't necessarily the most useful. What about just simply using an <object> tag, and letting people skim through the document inline. A click could then just open the PDF.

**Comment by ericadeahl** [comment]
A. I'm ok with eliminating the filter for the prototype, but it seems like an assumption that the file type isn't useful. I think we should look into what the actual breakdown of document types is and learn whether there is significance to potential users.

B. Agreed title name is better than no title. That's what the middle entry is in the mockup.

C. I'm ok with starting with PDFs if the body of documents we get ends up being mostly PDFs. But if there are lots of documents that are other file types, it seems arbitrary to only make PDFs available if it's not a large technical burden to include others (we could make them downloadable without including a preview of the doc.)

D. In the Related Documents section of your prototype, you just have the document title, but we've determined that many documents will not have helpful titles, so I thought it would be important to surface other data. Perhaps it would help to remove the "agency" "format" and "released" labels and put that data on a single line?

E. Would the documents be large enough to read without having the spaghetti box effect? What about mobile? I'd love to play around with the expanded inline viewer on the prototype to see what it would be like.

@khandelwal @rjmajma @vz3 @ramirezg

**Comment by khandelwal** [comment]
C. Making them downloadable without a preview would definitely be easier. Doing PDFs only does seem arbitrary, but it seemed like a good way to just limit the things we have to do before we can validate out in the open. I'm definitely open to this though. So, let's see if there are any other opinions. 

E. In a prototype where I didn't pick up the existing CSS and designs, the viewer window was definitely large enough to read a whole page. I'll need some front-end help to put up a version with a larger window. I don't think mobile would see a viewer at all.

**Comment by ericadeahl** [comment]
**Search landing page:**

![search landing 1](https://cloud.githubusercontent.com/assets/5911280/6587730/5b4e2dfe-c745-11e4-93c0-3150af05af45.png)

**Future version of search landing page with popular topics and agencies surfaced:**

![search landing 2](https://cloud.githubusercontent.com/assets/5911280/6587749/77833370-c745-11e4-824a-5f24efc89bd7.png)

**Search results - updated with format filter removed and metadata icons:**

![search results](https://cloud.githubusercontent.com/assets/5911280/6587758/a35e3d64-c745-11e4-8549-2716e900553f.png)

**Agency detail - with updated "related documents" section**

![agency detail](https://cloud.githubusercontent.com/assets/5911280/6587763/b9eb1372-c745-11e4-9ca9-ada43ceb5152.png)

**Alternate versions of "related documents" section**

![related documents options](https://cloud.githubusercontent.com/assets/5911280/6587783/f08daa0c-c745-11e4-8d01-60fff588de7f.png)

**Agency detail for CSV with no preview**

![agency detail csv](https://cloud.githubusercontent.com/assets/5911280/6587832/c65e35fc-c746-11e4-8b07-d38c0d9f93bd.png)

cc @khandelwal @vz3 @rjmajma @ramirezg @shawnbot

**Comment by konklone** [comment]
You're blowing my mind with how great this looks, and how exciting this project is.
