### ISSUE TITLE
Application should be able to force an HTTPS redirect

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#560]
We should be able to enforce HTTPS in our production environment, at the application level.

We also may need to add the HSTS header at this level.

**Comment by khandelwal** [comment]
Do this at the application layer.

**Comment by khandelwal** [comment]
I think I need more information on what this issue requires. What are we trying to achieve, and why are we trying to do it? 

I'm happy to try and implement this, but I don't currently understand everything.

**Comment by konklone** [comment]
@khandelwal Currently, redirects from HTTP->HTTPS are [handled by nginx](https://github.com/18F/foia-hub/blob/master/deploy/hub.conf#L83-L87), which sits in front of gunicorn on our EC2 instance.

In order for our app to be reachable to people who just type in our domain name without a protocol, or construct mistaken links that use `http://` in them, we need to have a redirector in place. That redirector is just something that is listening on port 80 for HTTP requests, and immediately sending an HTTP response with a 301 to the URL with an `https://` protocol.

Anything can send that redirect -- it doesn't have to be nginx, it's just commonly done there in setups that use a reverse proxy like nginx. It can also be performed by the application itself, if the application is not behind a proxy that has the capability to do that redirect itself.

The way 18F/DevOps plans to structure Cloud Foundry will mean that we terminate HTTPS on an ELB, and then send back plain HTTP requests (within the same VPC) to the Cloud Foundry router, which in turn forwards that request to our application. Responses will get passed through in the same way: from our Python waitress process, to the Cloud Foundry router, to the ELB, to the user. 

In theory, any of the nodes involved in that proxying could implement the HTTP->HTTPS redirect. In practice, Amazon ELBs don't give you an option to do redirects at the ELB layer (though ELBs will send a header to the next node that indicates what protocol the request used). And in practice, we're not ready to terminate HTTPS at the Cloud Foundry router, nor do we have the facility to send the redirect at the router level.

That means we need to implement the redirect in our app. In Django-land, that might be done by a middleware like [`django-sslify`](https://github.com/rdegges/django-sslify) or [`django-secure`](https://django-secure.readthedocs.org/en/latest/). Another aspect of HTTPS that has to be implemented at the HTTP level (instead of the TLS termination layer) is [HSTS](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security). `sslify` doesn't list HSTS support on its README, so `django-secure` might be the way to go.

If that's enough for you to go on, feel free to assign it back to yourself. If not, I can take this for the sprint.
