### ISSUE TITLE
Buy + Host Proxima

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#562]
Proxima will be bought and hosted by us.

**Comment by rjmajma** [comment]
After this is bought, someone else will need to help to host it.

**Comment by khandelwal** [comment]
- [ ] buy
- [ ] host

**Comment by rjmajma** [comment]
It's been bought! We're currently checking on some legal issues to determine how/where we can host it within our architecture.

**Comment by konklone** [comment]
Confirmed that GitHub is a no-go. We can put it in the S3 hosting bucket for the rest of our static assets, and manage it there. Since we're instrumenting that bucket automatically, we'll probably want a backup copy of the font elsewhere that 18F can access, like GSA's GDrive or an additional S3 bucket.

**Comment by konklone** [comment]
We'll also want to change the link to the font in our template code to always point to the S3 bucket, even when in development. So the steps remaining are:

- [ ] Put in FOIA assets bucket
- [ ] Back it up somewhere, or confirm it's already backed up
- [ ] Update template to point to the public URL for it

**Comment by vz3** [comment]
The font file is archived on Gdrive/Designers/Fonts

**Comment by vz3** [comment]
I will update the template to add URL and remove all ref's to TypeKit. Please let me know when the file is in the bucket.

**Comment by konklone** [comment]
I can't find the file in GDrive - please share it with me and @ramirezg and @khandelwal and one of us can get it in the bucket.

But @vz3, you should get bucket access too, even if it doesn't happen for launch.

**Comment by vz3** [comment]
Leaving some reference here:
http://www.metaltoad.com/blog/how-use-font-face-avoid-faux-italic-and-bold-browser-styles

@konklone do we have a URL yet for these?

**Comment by konklone** [comment]
@vz3 They're up, URL off-band.
