### ISSUE TITLE
Create an updated system diagram

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#576]
We're doing a whole bunch of devops related tasks, that came out of a meeting with the FOIA team and folks responsible for devops. 

It appears that the suggested architecture of our application has changed from what was diagrammed in early days. (For example, we're now talking about ELBs - and we weren't before). 

Let's get a new diagram together, so that we can better understand what's happening with all the changes.

**Comment by rjmajma** [comment]
I'd like to add this to the current sprint. I don't know if we have to have this for the current ATO authority we'll be operating under, but this kind of documentation will be helpful for understanding how our system works

**Comment by khandelwal** [comment]
This has been added to the current sprint, and assigned to the person who has the most knowledge of the updated system architecture.

**Comment by konklone** [comment]
From @seanherron, something to work off of:

![pasted_image_at_2015_03_04_02_25_pm](https://cloud.githubusercontent.com/assets/4592/6491498/847ee80e-c27b-11e4-9684-d5a2d61cea32.png)

**Comment by khandelwal** [comment]
Are we anywhere we doing this? We're going a lot of devops work - but I personally still don't have a complete picture of how everything fits together. I think that would be nice for me and others to have.

**Comment by konklone** [comment]
I'm still up for doing it, but it seems lower priority than the other DevOps tasks this sprint. I also think that if the team's developers are confused about the overall system architecture, the first and better step is taking a few minutes to whiteboard it out at our next team meeting and explain it to everyone. I know that'd also help me better understand what to even make for this.

**Comment by rjmajma** [comment]
Wait, I'm confused. The goal of something like this diagram is to chart out how our infrastructure works. Are we standing up tools in our VPC and not sure how they all work together?

**Comment by konklone** [comment]
We're no longer using our VPC - everything we deploy is going into the Cloud Foundry VPC. And to me, it's pretty clear how things work together, but that's probably because I've worked with our AWS footprint more than the rest of the team. Since there's confusion, let's cover this at our next meeting, but there's not going to be anything we haven't talked about already.

**Comment by khandelwal** [comment]
If you're going to whiteboard it at a meeting, just whiteboard it now on a piece of paper, take a picture and stick it in here. Seriously.

**Comment by khandelwal** [comment]
And if it's clear to you how things work, it won't take you but 15 minutes to start putting it together.

**Comment by konklone** [comment]
> And if it's clear to you how things work, it won't take you but 15 minutes to start putting it together.

I'll be sure to identify from afar when I think your tasks look simple enough to take 15 minutes, too. ;) It feels to me like something that will take me much longer than that, and I think my time is better spent on the tasks in this sprint that are actually preventing our system from being released.

Nonetheless, I'll draw up something on a whiteboard and photograph it and stick it in here, before the sprint is concluded.

**Comment by khandelwal** [comment]
I've put together a version of the diagram. 

![openfoia-cloud-foundry-architecture](https://cloud.githubusercontent.com/assets/636752/6696065/be1cfd4e-ccbc-11e4-8c26-3bd194067d02.png)

Does this make sense @dlapiduz @seanherron?

**Comment by khandelwal** [comment]
Notes: 

1. HTTPS terminates at the ELB. 
2. The ELB points to the Cloud Foundry routers. 
3. If we have multiple Cloud Foundry instances, only one of those should write to the database (load data).

**Comment by dlapiduz** [comment]
The diagram looks very good, the only thing I would mention is that Cloud Foundry is inside the Cloud Foundry VPC, not outside.

**Comment by khandelwal** [comment]
![openfoia-cloud-foundry-architecture 1](https://cloud.githubusercontent.com/assets/636752/6786802/db1dd574-d164-11e4-9e88-c83d035d562a.png)
