### ISSUE TITLE
Search results should show up even if <=1 results returned

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#579]
This was an experiment, but consensus is that it's a confusing interaction.

1. User on home page enters "FBI"
2. User is brought to search results page with 1 result.

**Comment by khandelwal** [comment]
Can you provide more detail? What does it do now? What do you want it to do?

**Comment by vz3** [comment]
Above is what I want it to do. Currently if user enters a query with 1 result they are brought to the landing page of that result.

**Comment by khandelwal** [comment]
@ramirezg You self-assigned this a while back. Do you intend to work on it this sprint? In that case - change the milestone.
