### ISSUE TITLE
Breadcrumbs should output current page name and URL

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#580]
Currently breadcrumbs only output parent pages. They should be changed to output the current page as well.

**Comment by khandelwal** [comment]
Can you provide more detail here? What is the current state, and what do want it to look like when it's done?

**Comment by vz3** [comment]
…the current state is that  breadcrumbs only output parent pages.

The desired state is that the current page is output.

i.e. for "Understanding FOIA", breadcrumb currently outputs:
[Home >](#)

It should output:

[Home] > Understanding FOIA
