### ISSUE TITLE
UX/Front-end help for contact-updater

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#581]
Forms for pages like DoD are too long and look terrible. 
https://foia.18f.us/contact_updater/department-of-defense
The contact updater needs a UX/front-end makeover.

**Comment by rjmajma** [comment]
Assigning to @ericadeahl for the time being. Happy to speak to you and @vz3 about this for more context or help.

**Comment by ericadeahl** [comment]
@ramirezg @rjmajma The link in this issue is broken. Can one of you send me a new link / screenshot / describe what you need here?

**Comment by khandelwal** [comment]
New link: https://foia.18f.us/update-contacts/department-of-defense

**Comment by rjmajma** [comment]
Just spoke to @vz3. He's going to schedule a small design studio to help push this along.

**Comment by vz3** [comment]
Form specs here:
https://docs.google.com/a/gsa.gov/spreadsheets/d/1gp4EPHTBfNFRoba-AWvmLZ_HEtpzPUeDaPJXApIalzE/edit?usp=sharing

**Comment by khandelwal** [comment]
Design studio was held. 
Next step is to do a wireframe.
