### ISSUE TITLE
CSRF cookies set without HttpOnly flag

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#586]
Reproducing @NoahKunin's issue, https://github.com/18F/DevOps/issues/259

**Comment by khandelwal** [comment]
Context: 

This allows the cookie to be accessed by JavaScript. This doesn't matter given current functionality, but will be necessary once form submission is enabled. Seems smart to catch it now so we don't have to deal with it later.

Note that Django has a relatively new feature that allows you to do this.

I can't map out all the JS, so if it needs to be accessed, let me know what's up.

**Comment by NoahKunin** [comment]
:+1:
