### ISSUE TITLE
Start a parallel domain name negotiation

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#593]
It's not clear if we'll get our current set of negotiations all worked out. Seems like there are two sticking points there: DNSSEC and glue records.

We should start talking to others to figure out where openFOIA can live. We've considered usa.gov (openfoia.usa.gov) but looking at the content on the site, what we have is a bit of deviation from the content that's there. 

There's also the option of trying for openfoia.gov (which is harder, but might make more sense long term because the strong association between the domain name and our branding).   In either case, let's start talking to others so that things are  in place should we need to move to our second choice for domain names.

**Comment by khandelwal** [comment]
cc: @rjmajma

**Comment by rjmajma** [comment]
Keeping open, but may not be necessary.

**Comment by rjmajma** [comment]
Unnecessary!
