### ISSUE TITLE
Better 500, 404 error templates - Now frontend tweaks

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#594]
We need better 404 and 500 error templates. Here's what the pages look like currently: 

![screen shot 2015-03-04 at 11 12 45 am](https://cloud.githubusercontent.com/assets/636752/6487513/97f744c4-c25f-11e4-9b33-ae4fc2b5d00e.png)

We might want to consider styling the 403, and 400 pages as well. 

![screen shot 2015-03-04 at 10 49 57 am](https://cloud.githubusercontent.com/assets/636752/6487523/a792f4a0-c25f-11e4-8492-0e2061272d60.png)

However the 404 and 500 pages are probably the most likely to be seen be viewers. 

See: https://docs.djangoproject.com/en/1.6/topics/http/views/#the-404-page-not-found-view (but we don't need a custom view). 

Task completion list: 

- [x] Design 404 page
- [x] Implement 404.html template in template root directory
- [x] Design 500 page
- [x] Implement 500.html template in template root directory

**Comment by khandelwal** [comment]
@ericadeahl I think this'll need to go to you first.

**Comment by khandelwal** [comment]
@khandelwal Put in a template that can be styled.

**Comment by khandelwal** [comment]
#657 Adds in basic template code for the 404 and 500 pages. So that those place holders exist when we're reading to implement these pages. 

Here's what the 404 page looks like: 
![screen shot 2015-03-23 at 4 03 31 pm](https://cloud.githubusercontent.com/assets/636752/6789428/9345d08c-d176-11e4-839c-ddae5220a1d6.png)

**Comment by khandelwal** [comment]
Make autocomplete work.

**Comment by rjmajma** [comment]
Provide extra padding at the top. That's a note for @vz3 if possible.

**Comment by vz3** [comment]
I will take autocomplete, padding, and formatting.
