### ISSUE TITLE
Do data loading from its own app

### ISSUE THREAD

**Issue by konklone** [18F/foia-hub#614]
Our manifest should have two "apps": one to serve web requests, one to do data loading.

This way, if we deploy multiple instances of the app, they're not all loading data simultaneously and running into horrible race conditions.

**Comment by konklone** [comment]
OK, since this is not strictly necessary for our launch, I'm at least bumping it to the next sprint. It's definitely the better way to go, but is not quite as trivial as I first thought. This and #615 mean that the DB migration step will also need to be removed from the "web" apps' deploy process and moved to the "data" app's process. We'll also have to make sure that both deployments succeed before switching the symlink (routes) in our new zero downtime deploy process.

It also makes me wonder if we should think again about how to manage updating data. Should we have to do a full application deploy to update data? Should that happen automatically, or manually? Both our current strategy, and this plan, strike me as interim workarounds -- which is fine, but we should at least figure out what the real plan should be.

**Comment by ramirezg** [comment]
Solved with the instances env var.
