### ISSUE TITLE
Implement new favicon

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#622]
@ericadeahl can you please share the sketch file?

**Comment by vz3** [comment]
## 16x16
![favicon-16x16](https://cloud.githubusercontent.com/assets/582918/6612488/8a2f2f92-c853-11e4-8335-e6bea2e61790.png)

## 32x32
![favicon-32x32](https://cloud.githubusercontent.com/assets/582918/6612490/8a35ed64-c853-11e4-97d6-527094032ea2.png)

## 96x96
![favicon-96x96](https://cloud.githubusercontent.com/assets/582918/6612489/8a347100-c853-11e4-8d15-e48112285d67.png)

## 194x194
![favicon-194x194](https://cloud.githubusercontent.com/assets/582918/6612491/8a372472-c853-11e4-9c30-e5c4d035b853.png)

## iOS: 180

![apple-touch-icon-180x180](https://cloud.githubusercontent.com/assets/582918/6612492/9f31bad6-c853-11e4-8e57-518639a9ccbc.png)

**Comment by rjmajma** [comment]
This was merged in a PR. Closing!
