### ISSUE TITLE
Look at Krang wireframes, and determine the changes that are required on the backend

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#628]
We have set of excellent wireframes for Krang. These will likely require changes to how we have search setup. 

- [x] List of backend changes that are required
- [x] Of that list of changes, determine which ones we'll work on during Sprint 16
- [x] Create issues for those backend changes

**Comment by khandelwal** [comment]
@ramirezg Can you document this with the changes we identified?

**Comment by ramirezg** [comment]
Below is a list of changes of changes. They seem like a lot but most are small. We should be able to finish most before the end of the sprint.

### Model Changes
Add model field for page number #638
Add model field for file extension #635 
Extract page numbers when possible. #641

### Elasticsearch Changes
Implement ability to sort documents by date. #634

### Template Changes
Display additional information on details page (MLT) - agency, released date, and extension #640 
Display additional information on details page - agency, foia contact page, created date, released date, number of pages #639
Display additional information on search page - Agency/Office, File Type, Released date, Created date #636
Show filename if title not present. #637 

### DevOps related issues
Merge upstream from foia-hub #645
Start working requirements to deploy on CF #644
Update import pipeline #643
