### ISSUE TITLE
Making reading rooms more prominent

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#629]
We display reading rooms or 'FOIA libraries' on our agency landing page, but we don't clearly indicate that users should maybe check out the reading rooms first before submitting a FOIA request. 

This would be useful as it is the intent of a reading room.

**Comment by rjmajma** [comment]
One additional possible change to the agency landing pages: 

We should consider how to communicate first-person requests (e.g., asking for your visa information or medical records). They're not always a part of the FOIA process. Some agencies process them within their FOIA shop and others do not. I think it's worth considering expressing that first-person requests are treated differently and do not necessarily fall under the FOIA.

**Comment by ericadeahl** [comment]
Here is a comp of the agency page - I removed the FOIA Library link from the sidebar and added it as an alert under the agency description.

I also made a change to the sidebar. Currently it lists the same phone number twice and lists a "public liaison" (see screenshot below the new comp), but it's not clear what that contact information is for - ie when do I contact the public liaison and when do I use the "submit a request" information below. I think changing the title to "Have questions?" helps explain the distinction.

@rjmajma 

![agency detail](https://cloud.githubusercontent.com/assets/5911280/6734502/aef54c54-ce15-11e4-8a62-b7088accd161.png)

Sidebar on current site:

![screen shot 2015-03-19 at 8 59 30 am](https://cloud.githubusercontent.com/assets/5911280/6734603/4b61b938-ce16-11e4-9544-84616a373e7d.png)

**Comment by rjmajma** [comment]
There's still work to be done here, but this was a great attempt at compromising the content changes that were suggested to us. Awesome work all around, @ericadeahl. I'm comfortable closing it but will leave it open for review.

**Comment by ramirezg** [comment]
@ericadeahl These changes really highlight the purpose of all the data we collected :100: 

Sometimes the public liaison phone and the office phone are different. Any thoughts on how to deal with that?

**Comment by khandelwal** [comment]
We need to tweak this with new content from DOJ.
