### ISSUE TITLE
Contextual help: definitions for agency landing pages

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#630]
On the agency landing pages we use a lot of industry jargon such as 'FOIA Library' or 'Public Liaison'. Let's get nice user-friendly definitions on these lined up for the great day that we have contextual search.

**Comment by rjmajma** [comment]
Given @ericadeahl's changes to the agency landing page here, https://github.com/18F/foia-hub/issues/629#issuecomment-83683502, I'm not sure this is necessary. Either way, did not complete.

**Comment by rjmajma** [comment]
Bad raph! Didn't finish, but worth doing. Moving to next sprint.

**Comment by rjmajma** [comment]
Here are some terms that I believe would be helpful to provide additional information for. The definitions are pulled directly from foia.gov. 

[
   {
    "term”:”Complex Request",
    "definition":"A FOIA request that an agency anticipates will involve a voluminous amount of material to review or will be time-consuming to process."
  },
{
    "term”:”Public Liaison",
    "definition":"If you have any issues with how an agency or office is handling your request, you can call the number found here to talk with that agency or office’s FOIA Public Liaison, who will work to address your concerns."
  },
{
    "term”:”Request Service Center",
    "definition":"This is the name and phone number of a contact at each agency or office, where you can call and ask questions about your pending FOIA request. Much like with the FOIA Contact, each agency or office handles only the requests that have been sent to them, and can only answer questions on pending requests within their office."
  },
{
    "term”:”Simple Request",
    "definition":"A FOIA request that an agency anticipates will involve a small volume of material or which will be able to be processed relatively quickly."
  },
]

**Comment by noahmanger** [comment]
Just to bring her in, @meiqimichelle has also been looking to do this for EITI.

**Comment by meiqimichelle** [comment]
Totally. We are definitely implementing, just haven't gotten there yet. Need to work on other content/site dev work first. I'm thinking we're at least one sprint, more likely two, away from implementation of a glossary MVP on EITI. Def. keep me in the loop :D

**Comment by rjmajma** [comment]
Closed. Implementation is in #686
