### ISSUE TITLE
Get a version of Krang online somewhere

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#631]
Let's get a version of Krang deployed online somewhere so that the rest of the team can play with it, and we can start evaluating it for testing usability.

**Comment by khandelwal** [comment]
- [ ] decide to deploy in cloud foundry or not
- [ ] setup elasticsearch server

**Comment by ramirezg** [comment]
We have a search, but no docs. 
http://krang.cf.18f.us/documents/search/?q=test
