### ISSUE TITLE
Get in touch with CFPB and ask about their needs around reading rooms

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#632]
We'd initially established contact with the CFPB, and now just need to follow up with them. 

- [ ] let's figure out what we the goals of that conversation are
- [ ] prepare any advance materials
- [ ] schedule meeting

**Comment by khandelwal** [comment]
I've emailed them to try and setup a time, but haven't heard back yet.

**Comment by rjmajma** [comment]
Shashank did that today! What's the update?
