### ISSUE TITLE
Krang: start working requirements to deploy on CF

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#644]
- [x] add elasticsearch service to cloud foundry
- [x] setup elastic search instance
- [x] setup Krang to work from env variables. 
- [ ] figure out how to load documents

**Comment by ramirezg** [comment]
@ozzyjohnson has added elasticsearch service to cloud foundry, so once we get the rest of these we should be able to start testing.

**Comment by khandelwal** [comment]
How did you setup the elasticsearch instance?

**Comment by ramirezg** [comment]
@khandelwal I should have been clearer with the checkboxes. The service is there, but I haven't tested Krang on CF yet.

**Comment by ramirezg** [comment]
https://github.com/projectkrang/foia-hub/pull/16/files
