### ISSUE TITLE
Prepare usability testing plan for Krang

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#665]

**Comment by rjmajma** [comment]
Talked it over with Liz Goodman, who gave great feedback. It's not usability testing we're necessarily doing, but learning how to ask them how they'd research (without Krang) and then using Krang to do that testing.

**Comment by ericadeahl** [comment]
Script is here:
https://docs.google.com/a/gsa.gov/document/d/14-PqfQpbFF3BIsehoxu27pYkNrnBZausJ0rVU3XTvwI/edit
