### ISSUE TITLE
Krang usability testing with FOIA Requestors

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#666]
Schedule and execute usability testing with ~5 FOIA requestors

**Comment by khandelwal** [comment]
3 interviews scheduled later this week.

**Comment by ericadeahl** [comment]
@vz3 and I conducted 3 interviews last week and are scheduling 2 more. Notes and synthesis here:
https://drive.google.com/open?id=0B4-jR19N8nwmfnY3THZ1VjVtNVpvTGxQdXZIanZuTjZLODJ6VFRFYUE4bnpLQ3pXVjRmVGc&authuser=0

**Comment by rjmajma** [comment]
Please add links to notes here.

**Comment by rjmajma** [comment]
@ramirezg Needs to put notes up.

**Comment by ramirezg** [comment]
ok, my notes are up.
