### ISSUE TITLE
Research planning for how agencies can submit documents to Krang

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#668]
Meet to plan the research!

**Comment by vz3** [comment]
Potentially CFPB, GSA?

**Comment by rjmajma** [comment]
We had the meeting. Erica will provide a research plan soon.

**Comment by rjmajma** [comment]
Can we link to the research plan here?

**Comment by ericadeahl** [comment]
The research plan is here:

https://docs.google.com/a/gsa.gov/document/d/1WRqK4QkfAu_EZALjVhOHiC5bZoU9wW6DbGG795BGe68/edit

I expanded on the goals we discussed at the planning meeting, and this afternoon will flush out the structure for the interviews

**Comment by khandelwal** [comment]
Raph to review.

**Comment by rjmajma** [comment]
I've reviewed and left comments for Erica.

**Comment by rjmajma** [comment]
Use the research plan to inform future interviews.
