### ISSUE TITLE
Implement Route 53 changes to turn on open.foia.gov

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#684]
We'll have to make some changes in route 53. 

Details: https://github.com/18F/foia-hub/issues/553#issuecomment-85656380

**Comment by konklone** [comment]
Go to Route 53, visit the `open.foia.gov` hosted zone, create a new record set, select "Alias", and then select the correct production ELB from the dropdown.

**Comment by konklone** [comment]
Our production ELB is mis-tagged for some reason, which I've raised to our DevOps team.
