### ISSUE TITLE
Ensure New Relic works for production. 

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#685]
We've implemented the right things and make the right environment variable changes. Let's make sure we all know where to go to look at the dashboards, and what to look for.

**Comment by ramirezg** [comment]
Two tabs we should keep on eye on:
[Capacity Analysis Report](https://docs.newrelic.com/docs/apm/reports/other-performance-analysis/capacity-analysis-report) - Will tell us if the number of instances are meeting capacity. 
[Availability report](https://docs.newrelic.com/docs/alerts/alert-policies/downtime-alerts/availability-monitoring) - ping the app every 20 seconds to check if it's available. Each app needs to be configured with a url. So far only krang-staging is configured.
 

If needed we can also [creating custom reports for python](https://blog.newrelic.com/2012/09/11/introducing-capacity-analysis-for-python/).
