### ISSUE TITLE
Implement - Glossary

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#686]
Our site uses a number of very specific, sometimes legal terms (e.g., FOIA Public Liaison). We've identified them and defined them in #630, but now we need to implement them in a glossary. We've already done this with openFEC. 

![demo](https://cloud.githubusercontent.com/assets/1696495/6517562/2953d300-c351-11e4-836b-bc68c20ae862.gif)

This should be implemented on our site as well. @noahmanger's PR/work can be seen here: https://github.com/18F/openFEC-web-app/pull/53.

**Comment by khandelwal** [comment]
A newer issue replaces this one: https://github.com/18F/foia-hub/issues/719
