### ISSUE TITLE
Update the Current Mockups to Reflect Content Changes

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#693]
The current mockups should be updated to reflect the most recent content changes. These can be found here: https://docs.google.com/a/gsa.gov/document/d/1LdO4CVAf5wfYu9hqIKeqpFTqgYx3JEntJSsn0Ex2pIg/edit

This will help us share the work with our stakeholders.

**Comment by ericadeahl** [comment]
@rjmajma Here are updated mockups

**Homepage**

![homepage 1](https://cloud.githubusercontent.com/assets/5911280/6955741/b2d5d154-d897-11e4-94bc-c4d351e0b6c0.png)

**Homepage with "How does the process work?" graphic**

![homepage 2](https://cloud.githubusercontent.com/assets/5911280/6955744/be7a4274-d897-11e4-9cba-81ba9a9d57ac.png)

**About this project**

![about this project](https://cloud.githubusercontent.com/assets/5911280/6955756/0554514e-d898-11e4-89fe-5e0337364e99.png)

**Agency landing**

![agency detail](https://cloud.githubusercontent.com/assets/5911280/6955761/0ce66974-d898-11e4-9fbf-e74f739dd084.png)

**Agency detail with expanded definition**
 I know we've talked about porting in the FEC glossary tool - is that something you envision implementing right away? Here is one simple version of adding contextual help - let's discuss what to do here.

![agency detail 2](https://cloud.githubusercontent.com/assets/5911280/6955763/1361b8f8-d898-11e4-8664-cdfc11f1e6f0.png)

**Comment by corizarek** [comment]
@ericadeahl you are awesome! These are looking great!

**Comment by rjmajma** [comment]
This is great, @ericadeahl. Closing!
