### ISSUE TITLE
Implement - New Agency Landing Page Design

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#698]
The following designs need to be implemented.

![](https://cloud.githubusercontent.com/assets/5911280/6955761/0ce66974-d898-11e4-9fbf-e74f739dd084.png)

**Comment by khandelwal** [comment]
Here's what a current iteration (without front-end help) looks like: https://cloud.githubusercontent.com/assets/636752/6989345/594cb87c-da28-11e4-8fc2-973d2da7039e.png

**Comment by khandelwal** [comment]
Note, we've changed some of the language around libraries - which is why my implementation reads a bit differently.

**Comment by rjmajma** [comment]
This is a new ticket. Included in #715.
