### ISSUE TITLE
Krang's Cloud Foundary instance is in the wrong space

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#702]
The Krang Cloud Foundry instance is in the production space 'hub'. 
It should probably be in the staging space called 'staging'. 

Let's only keep production ready applications in the 'hub' space.

**Comment by khandelwal** [comment]
cc: @ramirezg

**Comment by ramirezg** [comment]
K I've cleared the production space of non-production apps
```
name     requested state   instances   memory   disk   urls   
foia     started           1/1         1G       1G     foia.cf.18f.us   
foia-b   stopped           0/1         1G       1G     foia-b.cf.18f.us   
foia-a   started           1/1         1G       1G     open.foia.gov, foia-a.cf.18f.us 
```
I'll be working on rebooting krang on the staging side.

**Comment by ramirezg** [comment]
We now have a staging version of krang with keystone pipeline documents. 
http://krang-staging.cf.18f.us/documents/search/?q=keystone+pipeline

Also if anybody can figure out why this is happening please, help. 
![screen shot 2015-04-07 at 11 32 34 am](https://cloud.githubusercontent.com/assets/4596845/7026810/fb693114-dd19-11e4-80ed-543738cdd287.png)
