### ISSUE TITLE
Facets urls broken on Krang

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#712]
Fix the url text.
![screen shot 2015-04-07 at 11 32 34 am](https://cloud.githubusercontent.com/assets/4596845/7026810/fb693114-dd19-11e4-80ed-543738cdd287.png)

**Comment by ramirezg** [comment]
I was able to recreate the problem using elasticsearch 0.2 which is on cloundfoundry. Basically, with es 0.2 `release_agency_slug` is not treated as a whole string, rather it is analyzed and indexed as multiple words.

**Comment by khandelwal** [comment]
What's the version of elasticsearch that we're using?

**Comment by ramirezg** [comment]
1.4.2

```bash
gabrielramirez$ curl -XGET 'localhost:9200' 
{
  "status" : 200,
  "name" : "Patsy Walker",
  "cluster_name" : "elasticsearch_gabrielramirez",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by khandelwal** [comment]
That sounds like a significant version difference. Can we get our
CloudFoundry instance updated?

**Comment by ramirezg** [comment]
18F/DevOps/issues/310
