### ISSUE TITLE
Fix styling for content updates

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#715]
**Homepage**
- [x] change “begin your federal…” text size to H1
- [x] in “how does the process work?” section, reduce bottom margin after H2 (ie "1. identify an agency") to .5em (if that doesn't mess things up elsewhere) and increase the padding between the end of the body copy ("…a list of all federal agencies.") and the next header ("2. Do your research")

should look like this:
![screen shot 2015-04-08 at 3 57 05 pm](https://cloud.githubusercontent.com/assets/5911280/7057567/d2d81bdc-de0b-11e4-96c2-e8156e0e810f.png)

**About this Project**
- [x] add a rule at end of section "openFOIA aims..." and increase padding between end of section and beginning of new section "Getting better”. Match the spacing between “Getting Better” and “Current Features"
- [x] in “Current Features” reduce the padding above “searchable contact information” and increase the padding above and below the other thin rules

should look like this: 
![screen shot 2015-04-08 at 4 02 58 pm](https://cloud.githubusercontent.com/assets/5911280/7057575/ee36ec0a-de0b-11e4-9fdb-0dd2d2d77276.png)

**Agency pages**
- [x] when there is a public liaison, add a line break between “public liaison” and the phone number so they're not on the same line
- [x] in the white side bar text, add a little spacing after titles and between entries (like .5em)

![screen shot 2015-04-08 at 4 05 46 pm](https://cloud.githubusercontent.com/assets/5911280/7057730/d6943128-de0d-11e4-92d9-2000f87873e9.png)

- [x] add gray box behind “before you submit a FOIA request” text and add spacing above “submit a request” section
- [x] add bullet points before “browse the agency’s FOIA Library” and “check the agency’s website"

should look like this:
![screen shot 2015-04-08 at 4 05 42 pm](https://cloud.githubusercontent.com/assets/5911280/7057754/03d1db0e-de0e-11e4-9b09-c9f49cf121c8.png)

**Comment by vz3** [comment]
Closed with #732
