### ISSUE TITLE
Design studio for Krang agency library page

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#716]
Schedule and conduct a design studio with the team to sketch and discuss the agency library page

**Comment by ericadeahl** [comment]
Here are notes from the conversation with Marty in the design studio:
https://docs.google.com/document/d/1MdEDQ50A5CTMlqKL4YaZBHE_CAlPdAODpsfEJ_kNsy0/edit

Here are the sketches that came out of the studio:

**Agency library page**
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/5911280/7127053/cc5c9742-e1f3-11e4-8704-48b9b527a502.jpg)

![img_0057](https://cloud.githubusercontent.com/assets/5911280/7127141/c79fa4a0-e1f4-11e4-8905-02c6fa9e231e.JPG)

![img_2708](https://cloud.githubusercontent.com/assets/5911280/7127121/914450c2-e1f4-11e4-90f1-e635c6e82c48.JPG)

![img_2709](https://cloud.githubusercontent.com/assets/5911280/7127122/959ab8dc-e1f4-11e4-8c3b-f5c2bf075906.JPG)

![img_2710](https://cloud.githubusercontent.com/assets/5911280/7127123/99a0bc7e-e1f4-11e4-8ff1-26fd8fcffe7c.JPG)



**Integrating document search + agency info**

![img_0058](https://cloud.githubusercontent.com/assets/5911280/7127145/dc09a774-e1f4-11e4-8fed-b2c25277aadf.JPG)

![img_2711](https://cloud.githubusercontent.com/assets/5911280/7127128/9f7a42aa-e1f4-11e4-8cc8-8c0211f051e7.JPG)
![img_2712](https://cloud.githubusercontent.com/assets/5911280/7127129/a1dbc6e0-e1f4-11e4-89c7-f4e094444249.JPG)

![img_2713](https://cloud.githubusercontent.com/assets/5911280/7127132/a9c4b1b4-e1f4-11e4-8eaf-191a21ea16ce.JPG)

**Comment by ericadeahl** [comment]
@vz3 could you please post the rest of the sketches

**Comment by vz3** [comment]
# MM
![image](https://cloud.githubusercontent.com/assets/582918/7192766/a119adc0-e466-11e4-8ffc-81fa7b9bd94a.png)
![image](https://cloud.githubusercontent.com/assets/582918/7192770/a689d636-e466-11e4-9f9b-0143522ca26f.png)

# VZ
![image](https://cloud.githubusercontent.com/assets/582918/7192772/adcfb33e-e466-11e4-9d78-323ebfb2185c.png)
![image](https://cloud.githubusercontent.com/assets/582918/7192780/b5a59718-e466-11e4-8ade-3193e6aff7f3.png)
![image](https://cloud.githubusercontent.com/assets/582918/7192783/ba155dd8-e466-11e4-959e-94e3cbfc4520.png)

**Comment by ericadeahl** [comment]
Thank you! Closing this issue. Also saving these docs in Drive along with our planning notes:

https://drive.google.com/drive/u/0/#folders/0BwIuL4Fu2PENVFhRXzdIN1FHdFE/0B5ZkkkN_EN7iZklXUTZvcVpQX3M/0B4-jR19N8nwmflBLRzE1VS1oZVVRUDd2NHpQT1Y4WWl5Q0NxLWRadGh4Ykh5bDg2b0VYRjg
