### ISSUE TITLE
Design comps for Krang agency library page

### ISSUE THREAD

**Issue by ericadeahl** [18F/foia-hub#717]
Take the output from the design studio and refine into a design comp

**Comment by ericadeahl** [comment]
First pass based on results of the design studio:

![agency detail](https://cloud.githubusercontent.com/assets/5911280/7509484/22250b0a-f446-11e4-80f0-e2a5767dcbd6.png)

**Comment by khandelwal** [comment]
This is ready to be implemented. We'll iterate on the design a little bit later.
