### ISSUE TITLE
Write the FOIA Anthem

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#718]
The FOIA Anthem, sung to the tune of _________, will be performed by @ericadeahl during sprint review.

**Comment by nsinai** [comment]
https://www.youtube.com/watch?v=DhlPAj38rHc

**Comment by rjmajma** [comment]
I will play the ukelele.

**Comment by khandelwal** [comment]
Requests grow and FOIA producing
We all go working 
Some go searching
Everyone's got to make a living

Don't be fooled by the docs that I got
I'm still, I'm still FOIA from the block, 
Used to have a little, now I have a lot
No matter where I go, I know where I came from (iron mountain, ya'll)

[chorus]

From in cardboard boxes to email bits
To On the 6 to radio to headline clips
I stay grounded as the requests roll in
I'm real, I thought I told you
I really am all opener
Nothin phony, don't hate on me
What you get is what you request

[chorus]

I'm down to the earth like this
Rockin' this business
I've grown up so much, 
I'm redacting and hating it
Rumors got me laughing, kid
Love my life and my public
America first
Then can't forget to stay real
To me it's like breathing

[chorus]

It takes hard work to find it, 
So don't be fooled by the docs that I got, they assets 
I publish what I find out
Even if you take the bad route
Can't count the truth out
After a while, you know who to blink with
Just keep it real with the ones came in with
Best thing to do is ask now, request and stay low
Act like they don't, but they slow 

[chorus]
[chorus]

**Comment by khandelwal** [comment]
Lyrics are presented with artistic license, and a certain amount of fun. Opinions expressed are mine.

**Comment by corizarek** [comment]
Bravo, @khandelwal. Bravo. Never pegged you as a J-Lo enthusiast but I like it.
