### ISSUE TITLE
Create a glossary feature for the agency landing page

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#719]
- [x] Figure out what we want to do as an MVP
- [x] Implement glossary

**Comment by khandelwal** [comment]
Keep this as simple as possible.

**Comment by ericadeahl** [comment]
Discussed this with @vz and we decided to implement the expanding side box proposed in #693 

To ensure accessibility, we discussed adding explanatory text next to the (?) link. I think it might be sufficient to make the term part of the link (option 1 below.) If not, we can add "What is this?" text (option 2 below.)

![screen shot 2015-04-13 at 3 30 00 pm](https://cloud.githubusercontent.com/assets/5911280/7126883/20ccc09c-e1f2-11e4-8db0-6a9d98cbda04.png)

**Comment by khandelwal** [comment]
So, it turns out that @theresaanna has some free time and has graciously agreed to help out with this issue. I think it's self contained enough to be handed over pretty easily. 

I'm assigning this to her, and we can that much closer to releasing soon.

**Comment by khandelwal** [comment]
I've added in the correct definitions to the pull request.
