### ISSUE TITLE
Wireframe for contact updater

### ISSUE THREAD

**Issue by vz3** [18F/foia-hub#723]
Continued work on #581. Produce wireframes based on work from design studio.

**Comment by vz3** [comment]
![desktop copy 6](https://cloud.githubusercontent.com/assets/582918/7497949/7949aa68-f3eb-11e4-94f2-fe09639872c7.png)
![desktop copy 7](https://cloud.githubusercontent.com/assets/582918/7497953/794d7b16-f3eb-11e4-9e96-4e868d5d7716.png)
![desktop copy 8](https://cloud.githubusercontent.com/assets/582918/7497951/794b9f4e-f3eb-11e4-8ee7-d0cd135463c4.png)
![desktop copy 9](https://cloud.githubusercontent.com/assets/582918/7497950/7949b42c-f3eb-11e4-8836-320f165cfa15.png)
![desktop copy 10](https://cloud.githubusercontent.com/assets/582918/7497952/794c8684-f3eb-11e4-8f76-bc44debba9e6.png)
![desktop copy 12](https://cloud.githubusercontent.com/assets/582918/7497954/794f62be-f3eb-11e4-867e-59b4d89bda41.png)
![desktop copy 14](https://cloud.githubusercontent.com/assets/582918/7497955/79505e80-f3eb-11e4-9716-4d0ed500a532.png)

**Comment by vz3** [comment]
A more fleshed out take on a centralized agency. Probably going to want to take down the full width to ~18col in the final.
![desktop copy 15](https://cloud.githubusercontent.com/assets/582918/7515198/d919692c-f492-11e4-8146-64cd3d9442d4.png)

**Comment by khandelwal** [comment]
Let's implement this.

**Comment by ramirezg** [comment]
These look great! :+1:

**Comment by vz3** [comment]
Iterating on the design — dropdown navigation for decentralized agencies.

## Agency selection
![desktop copy 6](https://cloud.githubusercontent.com/assets/582918/7598823/27c85c7c-f8cb-11e4-8366-1e0e969f9ce8.png)
![desktop copy 7](https://cloud.githubusercontent.com/assets/582918/7598826/27cdc928-f8cb-11e4-834e-82fee8693132.png)
![desktop copy 8](https://cloud.githubusercontent.com/assets/582918/7598827/27ce38ae-f8cb-11e4-92c3-26e8c4d50735.png)
![desktop copy 9](https://cloud.githubusercontent.com/assets/582918/7598824/27cca494-f8cb-11e4-8ab0-21a2d6d55d28.png)
![desktop copy 10](https://cloud.githubusercontent.com/assets/582918/7598825/27cd3c88-f8cb-11e4-8f5b-9c802b85e78a.png)

## Centralized agency (full)
![desktop copy 15](https://cloud.githubusercontent.com/assets/582918/7598829/27cffb1c-f8cb-11e4-8425-de712e376cff.png)

## Decentralized agency
![desktop copy 16](https://cloud.githubusercontent.com/assets/582918/7598828/27cee768-f8cb-11e4-9b70-222f6ea427eb.png)
![desktop copy 17](https://cloud.githubusercontent.com/assets/582918/7598830/27d45518-f8cb-11e4-9f54-fa06831b7b48.png)
