### ISSUE TITLE
Design Research - Comparable Research Tools to Krang

### ISSUE THREAD

**Issue by rjmajma** [18F/foia-hub#724]
We're looking to create a research tool for records. Let's make sure we have a clear understanding of what else is out there and what users are using.

**Comment by ericadeahl** [comment]
collect screenshots from lexus nexis, mendeley, jstor, muck rock, etc

**Comment by rjmajma** [comment]
Raph to add notes about lexis nexus and westlaw.

**Comment by ericadeahl** [comment]
Here's a google doc I started in which I'm collecting screenshots from various sources, categorized by feature (basic search, advanced search, document view, agency page) and adding notes about interesting features. Please review and add any additional sources @vz3  @rjmajma

https://docs.google.com/document/d/1m6GUlfh--SjbtYQ49ovC9c3q3mOvaDdeZX3z9xycvuA/edit

**Comment by khandelwal** [comment]
When we're done, can we post the PDF of the output here? Our public audience can not see our work in Google Docs.
