### ISSUE TITLE
Collect screenshots for current application 

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#734]

**Comment by khandelwal** [comment]
![8_-_developers](https://cloud.githubusercontent.com/assets/636752/7146747/c8cc69ba-e2c3-11e4-945c-39ea93d75ad7.png)

**Comment by khandelwal** [comment]
![7_-_about_this_project](https://cloud.githubusercontent.com/assets/636752/7146755/d3945b64-e2c3-11e4-925c-e8f300093e18.png)

**Comment by khandelwal** [comment]
![6_-_all_agencies](https://cloud.githubusercontent.com/assets/636752/7146762/d8772594-e2c3-11e4-9639-c75bb9f3c3d2.png)

**Comment by khandelwal** [comment]
![4_-_agency_landing](https://cloud.githubusercontent.com/assets/636752/7146767/ddac03c2-e2c3-11e4-8858-40a6ba419a8f.png)

**Comment by khandelwal** [comment]
![3_-_search_results](https://cloud.githubusercontent.com/assets/636752/7146772/e481cc2c-e2c3-11e4-8ce5-c6e4560b1dbd.png)

**Comment by khandelwal** [comment]
![5_-_agency_landing_2](https://cloud.githubusercontent.com/assets/636752/7146784/f3dac84a-e2c3-11e4-9981-5d7dc29c421b.png)

**Comment by khandelwal** [comment]
![2_-_home_-_search](https://cloud.githubusercontent.com/assets/636752/7146786/f8ee05d6-e2c3-11e4-816c-635d0894641d.png)

**Comment by khandelwal** [comment]
![1_-_home](https://cloud.githubusercontent.com/assets/636752/7146858/8553a1b6-e2c4-11e4-9be2-1d78b3af1f3d.png)

**Comment by khandelwal** [comment]
![screen shot 2015-04-14 at 4 48 20 pm](https://cloud.githubusercontent.com/assets/636752/7147041/16f0ee66-e2c6-11e4-915f-95336298d6df.png)

**Comment by khandelwal** [comment]
![screen shot 2015-04-14 at 4 55 34 pm](https://cloud.githubusercontent.com/assets/636752/7147194/1d7c5d82-e2c7-11e4-88e1-5d341e236ec0.png)

**Comment by rjmajma** [comment]
https://github.com/18F/foia-hub/wiki/Documentation-of-the-current-status-of-openFOIA

**Comment by khandelwal** [comment]
We have new banner text. 

![screen shot 2015-04-20 at 10 55 43 am](https://cloud.githubusercontent.com/assets/636752/7232922/449fe2a6-e74c-11e4-8969-2543aa0ff8cd.png)

And the new corresponding home page: 
![screen shot 2015-04-20 at 10 56 18 am](https://cloud.githubusercontent.com/assets/636752/7232931/4db6038e-e74c-11e4-92fc-7b450e1003bb.png)
