### ISSUE TITLE
Migrate apps to new CF version & stack

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#740]
3 options
```bash
# delete and recreate the app
# `cf push myapp -s cflinuxfs2`
# `stack: cflinuxfs2` to your `manifest.yml` file
```
- [ ] production apps
- [x] openfoia staging
- [ ] krang staging

**Comment by ramirezg** [comment]
Update: I just tried to upgrade, but the app crashed due to a Python issue. Don't upgrade until DevOps says the Python issue is resolved.

**Comment by khandelwal** [comment]
Is there a bug tracking the Python issue?

**Comment by ramirezg** [comment]
Devops has a trello card. I'll keep tabs on it.
