### ISSUE TITLE
Load Test

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#744]
Load test site to make sure it can at least run with 20 concurrent users.

**Comment by khandelwal** [comment]
The site has been load tested multiple times. In the process, we added file-system based caching to openFOIA. 

Now, with 4 instances, we can support about 800 concurrent users. It's unlikely at this point, that we'll anything close to that.

**Comment by khandelwal** [comment]
Related pull requests: 

https://github.com/18F/foia-hub/pull/757
https://github.com/18F/foia-hub/pull/755
https://github.com/18F/foia-hub/pull/752
https://github.com/18F/foia-hub/pull/768
