### ISSUE TITLE
RDS and ES Instance

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#745]
We need an RDS and Elastic Search instance so that our front-end developers and others that can help us don't need to setup the whole shebang

**Comment by ramirezg** [comment]
Documentation for using ES on AWS. https://www.elastic.co/webinars/elasticsearch-on-aws

**Comment by ramirezg** [comment]
https://github.com/projectkrang/foia-hub/pull/23

**Comment by ramirezg** [comment]
separate the vagrant setup from Krang.

**Comment by ramirezg** [comment]
Ready for review [here](https://github.com/projectkrang/openfoia_vagrant/pull/1)

**Comment by ramirezg** [comment]
Vagrant box is merged and in use
