### ISSUE TITLE
Contact Scrubbing Article

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#747]
Article about the process of cleaning and validating FOIA contacts.

**Comment by ramirezg** [comment]
I have some time to start a rough draft.

**Comment by ramirezg** [comment]
[Here is the first rough draft](https://docs.google.com/document/d/1_JnWm9_hLRwr6gh5u2KWzqQNh5a7wbU6l-IDLeUvRy4/edit) I'd like to give it one more pass before having it reviewed.

**Comment by khandelwal** [comment]
There was a link here. But it's gone?

**Comment by ramirezg** [comment]
@khandelwal k it's back up

**Comment by khandelwal** [comment]
I've done a quick review of this. 
@rjmajma  You'll want to take a look too.

**Comment by khandelwal** [comment]
Let's do a second draft, but we can track that in a separate issue.
