### ISSUE TITLE
Find agency FOIA libraries we're going to get documents from

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#748]
A list of links to various agency/office FOIA libraries that we're going to download and display documents from for the very first release of Krang.

**Comment by rjmajma** [comment]
Agencies and offices: 
Department of Homeland Security
- We can skip USCIS given that their requests are largely first person.
Department of Defense
Department of Health and Human Services
U.S. Department of Justice
- We can probably skip the FBI for the time being, given how much that would be to process
Social Security Administration	
Department of Veterans Affairs
- We can skip any benefits or health records offices given that their requests are largely first person.
U.S. Department of Agriculture
National Archives & Records Administration
U.S. Department of Labor
United States Department of the Treasury
Department of Transportation
Securities and Exchange Commission
National Labor Relations Board
U.S. Department of the Interior
Central Intelligence Agency
