### ISSUE TITLE
Contact Updater Language

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#750]
Raph will take a first cut at copy and nudges we can provide to make sure we encourage agencies to update appropriately.

**Comment by rjmajma** [comment]
Completed a first pass on these.

**Comment by khandelwal** [comment]
Can you put the language here?

**Comment by rjmajma** [comment]
It'll be a bit hard to understand, but here is a link to the sheet: 

https://docs.google.com/a/gsa.gov/spreadsheets/d/1gp4EPHTBfNFRoba-AWvmLZ_HEtpzPUeDaPJXApIalzE/edit#gid=0

**Comment by rjmajma** [comment]
I'll consider this closed since the language has been provided.
