### ISSUE TITLE
Update with 2014 processing times

### ISSUE THREAD

**Issue by ramirezg** [18F/foia-hub#765]
New processing times are out.

**Comment by ramirezg** [comment]
https://github.com/18F/foia/pull/112

**Comment by khandelwal** [comment]
This has been merged. It needs to 

- [ ] Be deployed on staging and verified. 
- [ ] Be deployed into our production instance.

**Comment by rjmajma** [comment]
We should also do a spot check on any copy on the site to make sure we accurately reflect having 2014 data. I doubt we are that explicit, but we should make sure.

**Comment by khandelwal** [comment]
I don't think we have any of that copy. We should though. Maybe on the developer resources page?

**Comment by rjmajma** [comment]
+1

How about: 
`Much of the data we use is collected from Chief FOIA Officer Reports from data collected in 2014. We try to keep as current as possible, so please point out when things are out of date here [link].`

**Comment by khandelwal** [comment]
I think we only use the processing times, so we should specifically call that out. The contact information does not come from that source.

**Comment by rjmajma** [comment]
Good point. Updated above.

**Comment by khandelwal** [comment]
I'm going to add that copy to the 'About Page'

**Comment by khandelwal** [comment]
We're going to use this sentence instead: 

```The median processing times we use are from Annual FOIA Reports from data collected for 2014.```

Now approved by the DOJ.

**Comment by rjmajma** [comment]
You closing this or keeping it open? Make up your mind.

**Comment by khandelwal** [comment]
![screen shot 2015-04-29 at 5 40 03 pm](https://cloud.githubusercontent.com/assets/636752/7402054/cfc819f6-ee96-11e4-948f-a79dd3585c98.png)

**Comment by khandelwal** [comment]
This is what it's going to look like? You ok with that Raph?

**Comment by rjmajma** [comment]
Fine for now. Later we should update and say where all our data comes from.

**Comment by khandelwal** [comment]
Text is updated. Production is updated with new text and data.
