### ISSUE TITLE
search for "Department of State" returns too many results

### ISSUE THREAD

**Issue by batemapf** [18F/foia-hub#766]
https:XXXXX/agencies/?query=Department+of+State returns:

Displaying 19 results for
“Department of State”

    Department of State

    The Department of State advises the President and leads the nation in foreign policy issues. The State Department negotiates treaties and agreements with foreign entities, and represents the United States at the United Nations.
    Department of Energy

    The Department of Energy manages the United States' nuclear infrastructure and administers the country's energy policy. The Department of Energy also funds scientific research in the field.
    Department of the Air Force - Headquarters/ICIO (FOIA)

    The Air Force defends the United States in the air and space.
    Department of the Navy - Main Office

    The Navy's primary mission is to defend the United States.
    Department of Defense

    The Department of Defense provides the military forces needed to deter war, and to protect the security of the United States.
    Department of Commerce

    The historic mission of the Department of Commerce is "to foster, promote, and develop the foreign and domestic commerce" of the United States. This has evolved, as a result of legislative and administrative additions, to encompass broadly the responsibility to foster, serve, and promote the Nation's economic development and technological advancement.
    Department of Homeland Security

    Formed in 2002 from the combination of 22 departments and agencies, the Department of Homeland Security works to improve the security of the United States. The Department's work includes customs, border, and immigration enforcement; emergency response to natural and manmade disasters; antiterrorism work; and cybersecurity.
    Department of the Army - Freedom of Information and Privacy Office

    Focusing on land operations, the U.S. Army organizes, trains, and equips active duty and Reserve forces to preserve the peace, security, and defense of the United States.
    U.S. Coast Guard

    The U.S. Coast Guard safeguards the maritime interests of the United States and the environment around the world.
    Department of the Treasury

    The Department of the Treasury manages Federal finances by collecting taxes and paying bills and by managing currency, government accounts and public debt. The Department of the Treasury also enforces finance and tax laws.
    Department of Health and Human Services

    The Department of Health and Human Services protects the health of all Americans and provides essential human services.
    Department of Agriculture

    The Department of Agriculture provides leadership on food, agriculture, natural resources, and related issues.
    Department of Transportation

    The Department of Transportation is responsible for planning and coordinating federal transportation projects. It also sets safety regulations for all major modes of transportation.
    Department of Interior

    The Department of the Interior manages public lands and minerals, national parks, and wildlife refuges and upholds Federal trust responsibilities to Indian tribes and Native Alaskans. Additionally, Interior is responsible for endangered species conservation and other environmental conservation efforts.
    Department of Labor

    The Department of Labor administers a variety of federal labor laws to guarantee workers' rights to fair, safe, and healthy working conditions, including minimum hourly wage and overtime pay, protection against employment discrimination, and unemployment insurance.
    Department of Justice

    The Department of Justice works to enforce federal law, to seek just punishment for the guilty, and to ensure the fair and impartial administration of justice.
    Department of Housing and Urban Development

    The Department of Housing and Urban Development administers programs that provide housing and community development assistance. The Department also works to ensure fair and equal housing opportunity for all.
    Department of Education

    The mission of the Department of Education is to foster educational excellence and to ensure equal access to educational opportunity for all.
    Department of Veterans Affairs

    For information about VA medical care or benefits, write, call or visit your nearest VA facility.

**Comment by khandelwal** [comment]
This is expected behavior. A number of the descriptions for agencies contain the words 'Department' and/or 'United States' which yields numerous results for 'Department of State'. There are a couple things that make this behavior acceptable: 

1. Searching for text that might be in an agency name will result in auto-complete results. Users are most likely to click those. 

2. The agency name shows up at the top of the search results. 

I'm closing this as "works as designed".
