### ISSUE TITLE
List of agencies/offices without a FOIA Library link

### ISSUE THREAD

**Issue by khandelwal** [18F/foia-hub#769]
We need to provide DOJ with a list of the agencies/offices that don't have a specific FOIA Library link. In return, hopefully they will provide us with those links we might have missed.

**Comment by ramirezg** [comment]
[Here is a first pass at the list](https://gist.github.com/ramirezg/6075af2280f82e2d0eac) I'll double check tomorrow.

**Comment by ramirezg** [comment]
@rjmajma Should we just send this over to Jake?

**Comment by khandelwal** [comment]
Before we do that, let's go through this list, and see why we might have missed picking up any reading rooms.

**Comment by khandelwal** [comment]
Feel free to assign this to me if you like.

**Comment by rjmajma** [comment]
I believe Gabriel is on an airplane at the moment, so assigning to you Shashank.

**Comment by khandelwal** [comment]
I've done an exhaustive review of the missing reading rooms.

**Comment by khandelwal** [comment]
Department of Agriculture--Research, Education & Economics
  FOIA website is wrong: http://www.ars.usda.gov/Services/docs.htm?docid=1398
 
Department of Agriculture--Rural Development
  FOIA website is wrong: http://www.rd.usda.gov/contact-us/freedom-information-act-foia
  Note: There is no reading room on the page. 
  
United States Postal Service--USPS Headquarters Office
  Note: Code should have picked up reading room. 
  
United States Postal Service--USPS Field Office
  Note: Code should have picked up reading room. 
  
United States Postal Service--Postal Inspection Service
  Note: Code should have picked up reading room. 
 
United States Postal Service--Office of the Inspector General
  Note: Code should have picked up reading room. 
 
Department of Veterans Affairs--Central Office FOIA/Privacy Act Office
  Note: VA FOIA page does not load. 
  
[Cabinet level agencies removed, because they have de-centralized FOIA processing]  
  
Department of Homeland Security--Headquarters & Privacy Office
  Note: Link text is: Find FOIA Documents (http://www.dhs.gov/foia-library)
  
Department of Homeland Security--Office for Civil Rights and Civil Liberties
  Note: NO FOIA specific information on their website. 
  
Department of Homeland Security--Directorate for National Protection and Programs
  Needs manual override: http://www.dhs.gov/foia-library
  
Department of Homeland Security--Office of Operations Coordination and Planning
  Note: No FOIA specific information on their website. 
  
Department of Homeland Security--Science & Technology Directorate
  Note: No FOIA specific information on their website. 
  
Department of Homeland Security--Office of Biometric Identity Management
    Note: No FOIA specific information on their website. 
 
Department of Commerce--Economics and Statistics Administration Bureau
  Needs manual override: Main page is also reading room. http://www.esa.doc.gov/content/requesting-records-under-freedom-information-act
  
Department of Commerce--Economic Development Administration
  Needs manual override: http://www.osec.doc.gov/omo/FOIA/ereadingroom.htm
  
Department of Commerce--National Telecommunications and Information Administration
  No reading room. 
  
Department of Defense--Armed Services Board of Contract Appeals
  No reading room. 
  
Department of Defense--Defense Contract Audit Agency - Headquarters
  No reading room. 
  
Department of Defense--Department of Defense Education Activity
  FOIA page contains library: Manual override: http://www.dodea.edu/foia.cfm
  
Department of Defense--U.S. Africa Command
  FOIA page is incorrect: http://www.africom.mil/policies-guidance/freedom-of-information-act-requests
  FOIA page also contains reading room (needs manual override): http://www.africom.mil/policies-guidance/freedom-of-information-act-requests
  
Department of Defense--U.S. Southern Command
  FOIA page is completely incorrect: http://www.southcom.mil/foia/Pages/FOIA.aspx
  There is now a bug for this. 
 
Department of Defense--U.S. Special Operations Command
  We have the wrong FOIA website: http://www.socom.mil/foia/Pages/FOIARequesterServiceCenter.aspx
 
Department of Energy--Savannah River Operations Office
  We have the wrong FOIA website: http://sro.srs.gov/foia.html
  
Department of Energy--National Nuclear Security Administration Office of Naval Reactors
  Has no FOIA page
  
Department of Energy--Environmental Management Consolidated Business Center (EMCBC)
  Reading room is in a blocking light box only Javascript enabled. 
  Best link is: https://www.emcbc.doe.gov/About/FOIA (needs manual override)
  
Department of Energy--Southeastern Power Administration
  Incorrect page for FOIA. 
  Needs manual override: http://energy.gov/sepa/services/sepa-freedom-information-act-foia-program
  No electronic reading room. 
  
Department of Energy--National Energy Technology Laboratory
  FOIA page contains reading room: http://www.netl.doe.gov/home/foia (with one document)
  
Department of Interior--U.S. Geological Survey
  FOIA page is reading room: http://www.usgs.gov/foia/
  (There's no good way to detect these)
  
Department of Interior--Office of the Secretary
  Reading room (manual override): http://www.doi.gov/foia/os/index.cfm
  Site information architecture is too terrible to figure this out automatically. 
 
Department of Interior--Office of Surface Mining
  FOIA page is wrong. Correct page:  http://www.osmre.gov/lrg/foia.shtm
  We probably need to reload data from foia.gov. 
  Reading rooms will be picked up automatically. 
  
Department of Interior--Office of the Special Trustee
  No FOIA specific page. 
  No reading room. 
  
Department of Justice--Civil Division
  FOIA Website does not work. Also broken on foia.gov
  
  
Department of Justice--Civil Rights Division
  Link text is not what we look for: 
  Manual override: http://www.justice.gov/crt/foia/readingroom
  
  
Department of Justice--Executive Office for Organized Crime Drug Enforcement Task Forces
  No FOIA website. 
  
Department of Justice--Office of Information Policy
  Need to re-run data. 
 
Department of Justice--Office on Violence Against Women
  FOIA library is on the page: http://www.justice.gov/ovw/ovw-freedom-information-act
  Manual override. 
 
Department of Transportation--Saint Lawrence Seaway Development Corporation
  Manual override: http://www.seaway.dot.gov/publications/electronic-reading-room
  
 
Department of Transportation--Surface Transportation Board
  Manual override: http://www.stb.dot.gov/stb/foia.html
  
Equal Employment Opportunity Commission--Atlanta District Office (Savanna Local Office)
  No reading room
Equal Employment Opportunity Commission--Birmingham District Office (Mobile Local Office, Jackson Area Office)
  No reading room
Equal Employment Opportunity Commission--Charlotte District Office (Greensboro; Greenville, Norfolk, Richmond Local Offices; Raleigh Area Office
  NO reading room
Equal Employment Opportunity Commission--Chicago District Office (Milwaukee and Minneapolis Area Offices)
  No reading room
Equal Employment Opportunity Commission--Dallas District Office (San Antonio Field Office, El Paso Area Office)
  No reading room
Equal Employment Opportunity Commission--Houston District Office (New Orleans Field Office)
  No reading room
Equal Employment Opportunity Commission--Indianapolis District Office (Detroit Field Office, Cincinnati and Louisville Area Offices)
  No reading room
Equal Employment Opportunity Commission--Los Angeles District Office (Fresno, Honolulu, Las Vegas, and San Diego Local Offices)
  No reading room
Equal Employment Opportunity Commission--Memphis District Office (Little Rock and Nashville Area Offices)
  No reading room
Equal Employment Opportunity Commission--Miami District Office (Tampa Field Office and San Juan Local Office)
  No reading room
Equal Employment Opportunity Commission--New York District Office (Boston and Newark Area Offices, Buffalo Local Office)
  No reading room
Equal Employment Opportunity Commission--Philadelphia District Office (Baltimore and Cleveland Field Offices, Pittsburgh Area Office)
  No reading room
Equal Employment Opportunity Commission--Phoenix District Office (Denver Field Office, Albuquerque Area Office)
  No reading room
Equal Employment Opportunity Commission--San Francisco District Office (Seattle Field Office, Oakland and San Jose Local
  Offices)
    No reading room
Equal Employment Opportunity Commission--St. Louis District Office (Kansas City and Oklahoma Area Offices)
  No reading room
Equal Employment Opportunity Commission--Washington Field Office
  No reading room
  
  
Environmental Protection Agency--National Headquarters
  Text code searches for should be: FOIA Libraries (plural)
  
Environmental Protection Agency--Region 6 (States: AR, LA, NM, OK, TX)
  Should have been picked up by code: 
  http://www.epa.gov/earth1r6/6md/foia/reading.html
  
Environmental Protection Agency--Region 8 (States: CO, MT, ND, SD, UT, WY)
  FOIA page is incorrect
  Incorrect on foia.gov
  
Environmental Protection Agency--Region 9 (States: AZ, CA, HI, NV, AS, GU)
  manual override: http://www2.epa.gov/foia/foia-library-information-specific-epa-region-9
  
Environmental Protection Agency--Region 10 (States: AK, ID, OR, WA)
  FOIA page is incorrect (redirects)
  Incorrect on foia.gov
  manual override: http://www2.epa.gov/foia/foia-library-information-specific-epa-region-10
  
  
Federal Labor Relations Authority--San Francisco Regional Office
  manual override: http://www.flra.gov/elibrary
  
Federal Labor Relations Authority--Washington Regional Office
  manual override: http://www.flra.gov/elibrary
  
Federal Labor Relations Authority--The Federal Service Impasses Panel
  manual override: http://www.flra.gov/elibrary
  
Federal Labor Relations Authority--Office of the Inspector General
  manual override: http://www.flra.gov/elibrary
  
Merit Systems Protection Board--Headquarters
  no reading room
Merit Systems Protection Board--Atlanta Regional Office
  no reading room
Merit Systems Protection Board--Central Regional Office
  no reading room
Merit Systems Protection Board--Washington DC Regional Office
  no reading room
Merit Systems Protection Board--Northeastern Regional Office
  no reading room
Merit Systems Protection Board--Dallas Regional Office
  no reading room
Merit Systems Protection Board--Western Regional Office
  no reading room
Merit Systems Protection Board--New York Field Office
  no reading room
Merit Systems Protection Board--Denver Field Office
  no reading room
  
  
National Archives and Records Administration--Pacific Alaska Region (Anchorage)
  This office no longer exists. 
  A re-run of the data should solve?
  
National Archives and Records Administration--Southeast Region (Atlanta)
National Archives and Records Administration--Northeast Region (Boston)
National Archives and Records Administration--Great Lakes Region (Chicago)
National Archives and Records Administration--Rocky Mountain Region (Denver)
National Archives and Records Administration--Southwest Region (Fort Worth)
National Archives and Records Administration--Central Plains Region (Kansas City)
National Archives and Records Administration--Northeast Region (New York)
National Archives and Records Administration--Mid-Atlantic Region (City Center Philadelphia)
National Archives and Records Administration--Pacific Region (San Francisco)
National Archives and Records Administration--Pacific Region (Seattle)
 
I don't know how to deal with the Archives. Do they do FOIA?
 
 
National Aeronautics and Space Administration--Headquarters
  manual override: http://www.hq.nasa.gov/office/pao/FOIA/err.htm
  
National Aeronautics and Space Administration--Glenn Research Center
  manual override: http://www.grc.nasa.gov/WWW/FOIA/ReadingRm.htm
  
National Aeronautics and Space Administration--Johnson Space Center
  manual override: http://www.nasa.gov/centers/johnson/news/edocs.html
  
National Aeronautics and Space Administration--Kennedy Space Center
  FOIA main page is wrong. Data load should fix this. 
  Add to vocabulary: FOIA Electronic Library
  
National Aeronautics and Space Administration--Office of the Inspector General
  No reading room. 
  
National Aeronautics and Space Administration--Principal Agency FOIA Officer
  No reading room. 
  
National Credit Union Administration--Main Office
  No reading room
  
National Credit Union Administration--Office of the Inspector General
  No reading room. 
  
Department of the Treasury--Bureau of Fiscal Services
  http://www.fms.treas.gov/foia/frequentfoia.html
  
Department of Labor--Office of the Administrative Law Judges
  manual override: http://www.oalj.dol.gov/libfoia.htm
  
Department of Labor--Office of the Assistant Secretary for Administration and Management
  manual override: http://www.dol.gov/dol/siteindex.htm
  
Department of Labor--Office of Federal Contract Compliance Programs
  manual override: http://www.dol.gov/ofccp/ofccp-foia.htm
  
Department of Labor--Office of Labor-Management Standards
  manual override: http://www.dol.gov/olms/regs/compliance/OLMS_FOIA.htm
 
Department of Labor--Office of Workers' Compensation Programs
  manual override: http://www.dol.gov/owcp/foia/owcp-foia.htm
  
Department of Labor--Veterans' Employment & Training Service
  manual override: http://www.dol.gov/vets/foia/
  
Department of Labor--Wage and Hour Division
  manual override: http://www.dol.gov/whd/foia/
  
Department of Labor--Women's Bureau
  manual override: http://www.dol.gov/wb/e-foia.htm
  
Department of Agriculture--Agricultural Marketing Service
  Main FOIA page doesn't exist. 
  http://www.ams.usda.gov/AMSv1.0/ams.fetchTemplateData.do?template=TemplateN&navID=Home&topNav=Home&page=FOIA&description=Freedom%20of%20Information%20Act%20(FOIA)
  Maybe run a data load? 
  
Department of Agriculture--Food, Nutrition & Consumer Services
  Code should pick up
  http://www.fns.usda.gov/foia/electronic-reading-room
  
Department of Agriculture--Forest Service - Headquarters
  Add to vocabulary: frequently requested records
  
Department of Agriculture--Grain Inspection, Packers & Stockyards Administration
  FOIA website is incorrect. 
  Needs to be fixed on foia.gov
  Manual override (reading room): http://www.gipsa.usda.gov/foia/foia.aspx
 
Department of Agriculture--National Appeals Division
  manual override: http://www.nad.usda.gov/foia.html
  
Department of Agriculture--Natural Resources Conservation Service
  manual override: http://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/about/?cid=stelprdb1186403

**Comment by rjmajma** [comment]
...well okay then. That's a lot of great work.

**Comment by khandelwal** [comment]
- [ ] Send list of agencies with no reading room to Jake.
